function openExpTtpr(h_fig)

% Last update, 16.2.2020 by MH: save callbacks to separate files
% update, 10.4.2019 by MH: (1) link the "infos" button to online documentation (2) improve trace section (change "ASCII(*.txt)" trace file format to "customed format(*.txt)" and "VbFRET" to "vbFRET", improve informative text about the number of trace file per molecules and which traces are exported) (3) improve figure section (add informative text about the number of pages exported in one figure file depending on the chosen format, correct panel title's font weight to bold, correct extra space in GUI)
% update, 24.4.2018 by FS: add popup for exporting tagged molecules individually

h = guidata(h_fig);
p = h.param.ttPr;
proj = p.curr_proj;
FRET = p.proj{proj}.FRET;
S = p.proj{proj}.S;
exc = p.proj{proj}.excitations;
tagNames = p.proj{proj}.molTagNames;
tagClr = p.proj{proj}.molTagClr;

str_trFmt = {'customed format(*.txt)', 'HaMMy-compatible(*.dat)', ...
    'vbFRET-compatible(*.mat)', 'SMART-compatible(*.traces)', ...
    'QUB-compatible(*.txt)', 'ebFRET-compatible(*.dat)', 'All formats'};

str_trInfos = {'(individual files)', ...
    '(individual files) Donor and acceptor traces only.', ...
    '(one file) Donor and acceptor traces only.', ...
    '(one file) Donor and acceptor traces only.', ...
    '(individual files) Donor and acceptor traces only.', ...
    '(one file) Donor and acceptor traces only.', ...
    'Options set for customed format only.'};

str_prm = {'external file(*.log)', 'ASCII file headers', 'none'};
str_figFmt = {'Portable document format(*.pdf)', ...
    'Portable network graphics(*.png)', ...
    'Joint Photographic Experts Group(*.jpeg)'};

% added by MH, 10.4.2019
str_figInfos = {'All pages in on file.', ...
    'One file per page.', ...
    'One file per page.'};

str_figTopExc = getStrPop('plot_exc', exc);
str_figTopChan = getStrPop('plot_topChan', ...
    {p.proj{proj}.labels p.proj{proj}.fix{1}(1) p.proj{proj}.colours{1}});
str_figBotChan = getStrPop('plot_botChan', ...
    {FRET S exc p.proj{proj}.colours p.proj{proj}.labels});

wPan = 235;
mg = 10;
w_full_pan = wPan - 2*mg;
w_full_sub = wPan - 3*mg;

w_but = 60; h_but = 22;
w_edit = 35; h_edit = 20; 
w_med_big = 95;
w_pop = 125;
w_med = 90;
w_big = 110;
h_txt = 14;

hPan_tr =   9*h_edit + 2*h_txt + 9*mg + 3*mg/2;
hPan_hist = 6*h_edit + 2*h_txt + 6*mg + 3*mg/2;
hPan_dt =   6*h_edit +   h_txt + 7*mg + 2*mg/2;

% modified by MH, 10.4.2019
% hPan_fig =  10*h_edit +   h_but + 8*mg + 4*mg/2;
hPan_fig =  9*h_edit + h_txt +  h_but + 8*mg + 4*mg/2;

hFig = h_txt + h_but + max([(hPan_tr+hPan_hist),(hPan_dt+hPan_fig)]) + ...
    5*mg;
wFig = 2*wPan + 3*mg;
w_full_fig = wFig - 2*mg;

pos_0 = get(0, 'ScreenSize');
xFig = pos_0(1) + (pos_0(3) - wFig)/2;
yFig = pos_0(2) + (pos_0(4) - hFig)/2;
if hFig > pos_0(4)
    yFig = pos_0(4) - 30;
end
        
h.optExpTr.figure_optExpTr = figure('Color', [0.94 0.94 0.94], ...
    'Resize', 'off', 'NumberTitle', 'off', 'MenuBar', 'none', 'Name', ...
    'Export options', 'Visible', 'off', 'Units', 'pixels', 'Position', ...
    [xFig yFig wFig hFig], 'CloseRequestFcn', ...
    {@figure_optExpTr_CloseRequestFcn, h_fig});

xNext = mg;
yNext = hFig - mg - h_txt;

uicontrol('Style', 'text', 'Parent', h.optExpTr.figure_optExpTr, ...
    'String', ['If no other mention, one set of file is exported for ' ...
    'each molecule'], 'ForegroundColor', [0 0 1], 'Position', ...
    [xNext yNext w_full_fig h_txt], 'HorizontalAlignment', 'left', ...
    'FontSize', 10);

%% panel export traces

xNext = mg;
yNext = hFig - 2*mg - h_txt - hPan_tr;

h.optExpTr.uipanel_traces = uipanel('Units', 'pixels', 'Parent', ...
    h.optExpTr.figure_optExpTr, 'Title', 'Time traces', 'Position', ...
    [xNext yNext wPan hPan_tr], 'FontWeight', 'bold');

xNext = mg;
yNext = hPan_tr - 2*mg - h_edit;

h.optExpTr.radiobutton_saveTr = uicontrol('Style', 'radiobutton', ...
    'Units', 'pixels', 'Parent', h.optExpTr.uipanel_traces, 'String', ...
    'Export time traces', 'Position', [xNext yNext w_full_pan h_edit], ...
    'Callback', {@radiobutton_saveTr_Callback, h_fig});

xNext = mg;
yNext = yNext - mg - h_edit;

h.optExpTr.text_trFmt = uicontrol('Style', 'text', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_traces, 'String', 'Export format:', ...
    'Position', [xNext yNext w_med h_txt], 'HorizontalAlignment', 'left');

xNext = xNext + w_med;

h.optExpTr.popupmenu_trFmt = uicontrol('Style', 'popupmenu', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_traces, 'String', str_trFmt, ...
    'Position', [xNext yNext w_pop h_edit], 'Callback', ...
    {@popupmenu_trFmt_Callback, h_fig}, 'BackgroundColor', [1 1 1]);

xNext = mg;
yNext = yNext - mg/2 - h_txt;

h.optExpTr.text_trInfos = uicontrol('Style', 'text', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_traces, 'UserData', str_trInfos, ...
    'Position', [xNext yNext w_full_pan h_txt], 'HorizontalAlignment', ...
    'left', 'ForegroundColor', [0 0 1]);

xNext = mg;
yNext = yNext - mg - h_txt;

h.optExpTr.text_tr2exp = uicontrol('Style', 'text', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_traces, 'String', 'Traces to export:', ...
    'Position', [xNext yNext w_full_pan h_txt], 'HorizontalAlignment', ...
    'left');

xNext = 2*mg;
yNext = yNext - mg - h_edit;

h.optExpTr.checkbox_trI = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_traces, 'String', ...
    'intensity-time traces', 'Callback', ...
    {@checkbox_trI_Callback, h_fig}, 'Position', ...
    [xNext yNext w_full_sub h_edit]);

yNext = yNext - mg/2 - h_edit;

h.optExpTr.checkbox_trFRET = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_traces, 'String', ...
    'FRET-time traces', 'Position', [xNext yNext w_full_sub h_edit], ...
    'Callback', {@checkbox_trFRET_Callback, h_fig});

yNext = yNext - mg/2 - h_edit;

h.optExpTr.checkbox_trS = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_traces, 'String', ...
    'stoichiometry-time traces', 'Callback', ...
    {@checkbox_trS_Callback, h_fig}, 'Position', ...
    [xNext yNext w_full_sub h_edit]);

yNext = yNext - mg/2 - h_edit;

h.optExpTr.checkbox_trAll = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_traces, 'String', ...
    'all traces in one file', 'Callback', ...
    {@checkbox_trAll_Callback, h_fig}, 'Position', ...
    [xNext yNext w_full_sub h_edit]);

% added by FS, 19.3.2018
yNext = yNext - mg/2 - h_edit;

h.optExpTr.checkbox_gam = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_traces, 'String', ...
    'correction factors (*.gam,*.bet)', 'Callback', ...
    {@checkbox_gam_Callback, h_fig}, 'Position', ...
    [xNext yNext w_full_sub h_edit]);


xNext = mg;
yNext = yNext - mg - h_edit;

h.optExpTr.text_trPrm = uicontrol('Style', 'text', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_traces, 'String', 'Parameters:', ...
    'Position', [xNext yNext w_med h_txt], 'HorizontalAlignment', 'left');

xNext = xNext + w_med;

h.optExpTr.popupmenu_trPrm = uicontrol('Style', 'popupmenu', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_traces, 'String', str_prm, ...
    'Position', [xNext yNext w_pop h_edit], 'Callback', ...
    {@popupmenu_trPrm_Callback, h_fig}, 'BackgroundColor', [1 1 1]);

xNext = mg;
yNext = yNext - mg - h_edit;

h.optExpTr.radiobutton_noTr = uicontrol('Style', 'radiobutton', ...
    'Units', 'pixels', 'Parent', h.optExpTr.uipanel_traces, 'String', ...
    'No trace file', 'Position', [xNext yNext w_full_pan h_edit], ...
    'Callback', {@radiobutton_noTr_Callback, h_fig});


%% panel export histograms

xNext = mg;
yNext = hFig - 3*mg - h_txt - hPan_tr - hPan_hist;

h.optExpTr.uipanel_hist = uipanel('Parent', h.optExpTr.figure_optExpTr, ...
    'Units', 'pixels', 'Title', 'Histograms', 'Position', ...
    [xNext yNext wPan hPan_hist], 'FontWeight', 'bold');

xNext = mg;
yNext = hPan_hist - 2*mg - h_edit;

h.optExpTr.radiobutton_saveHist = uicontrol('Style', 'radiobutton', ...
    'Units', 'pixels', 'Parent', h.optExpTr.uipanel_hist, 'String', ...
    'Export histograms', 'Position', ...
    [xNext yNext w_full_pan h_edit], 'Callback', ...
    {@radiobutton_saveHist_Callback, h_fig});

xNext = mg;
yNext = yNext - mg - h_txt;

h.optExpTr.text_hist2exp = uicontrol('Style', 'text', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_hist, 'String', ...
    'Histograms to export:', 'Position', ...
    [xNext yNext w_full_pan h_txt], 'HorizontalAlignment', 'left');

xNext = mg + w_med_big;
yNext = yNext - mg/2 - h_txt;

h.optExpTr.text_min = uicontrol('Style', 'text', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_hist, 'String', 'min', 'Position', ...
    [xNext yNext w_edit h_txt], 'HorizontalAlignment', 'center');

xNext = xNext + mg/2 + w_edit;

h.optExpTr.text_bin = uicontrol('Style', 'text', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_hist, 'String', 'bin', 'Position', ...
    [xNext yNext w_edit h_txt], 'HorizontalAlignment', 'center');

xNext = xNext + mg/2 + w_edit;

h.optExpTr.text_max = uicontrol('Style', 'text', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_hist, 'String', 'max', 'Position', ...
    [xNext yNext w_edit h_txt], 'HorizontalAlignment', 'center');

xNext = mg;
yNext = yNext - h_edit;

h.optExpTr.checkbox_histI = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_hist, 'String', ...
    'intensities', 'Callback', {@checkbox_histI_Callback, h_fig}, ...
    'Position', [xNext yNext w_med_big h_edit]);

xNext = xNext + w_med_big;

perSec = h.param.ttPr.proj{h.param.ttPr.curr_proj}.fix{2}(4);
perPix = h.param.ttPr.proj{h.param.ttPr.curr_proj}.fix{2}(5);
tooltip = 'counts';
if perSec
    tooltip = [tooltip ' per sec'];
end
if perPix
    tooltip = [tooltip ' per pixel'];
end

h.optExpTr.edit_minI = uicontrol('Style', 'edit', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_hist, 'BackgroundColor', [1 1 1], ...
    'Position', [xNext yNext w_edit h_edit], 'Callback', ...
    {@edit_minI_Callback, h_fig}, 'TooltipString', tooltip);

xNext = xNext + mg/2 + w_edit;

h.optExpTr.edit_binI = uicontrol('Style', 'edit', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_hist, 'BackgroundColor', [1 1 1], ...
    'Position', [xNext yNext w_edit h_edit], 'Callback', ...
    {@edit_binI_Callback, h_fig}, 'TooltipString', tooltip);

xNext = xNext + mg/2 + w_edit;

h.optExpTr.edit_maxI = uicontrol('Style', 'edit', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_hist, 'BackgroundColor', [1 1 1], ...
    'Position', [xNext yNext w_edit h_edit], 'Callback', ...
    {@edit_maxI_Callback, h_fig}, 'TooltipString', tooltip);

xNext = mg;
yNext = yNext - mg/2 - h_edit;

h.optExpTr.checkbox_histFRET = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_hist, 'String', ...
    'FRET', 'Callback', {@checkbox_histFRET_Callback, h_fig}, ...
    'Position', [xNext yNext w_med_big h_edit]);

xNext = xNext + w_med_big;

h.optExpTr.edit_minFRET = uicontrol('Style', 'edit', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_hist, 'BackgroundColor', [1 1 1], ...
    'Position', [xNext yNext w_edit h_edit], 'Callback', ...
    {@edit_minFRET_Callback, h_fig});

xNext = xNext + mg/2 + w_edit;

h.optExpTr.edit_binFRET = uicontrol('Style', 'edit', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_hist, 'BackgroundColor', [1 1 1], ...
    'Position', [xNext yNext w_edit h_edit], 'Callback', ...
    {@edit_binFRET_Callback, h_fig});

xNext = xNext + mg/2 + w_edit;

h.optExpTr.edit_maxFRET = uicontrol('Style', 'edit', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_hist, 'BackgroundColor', [1 1 1], ...
    'Position', [xNext yNext w_edit h_edit], 'Callback', ...
    {@edit_maxFRET_Callback, h_fig});

xNext = mg;
yNext = yNext - mg/2 - h_edit;

h.optExpTr.checkbox_histS = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_hist, 'String', ...
    'stoichiometries', 'Callback', {@checkbox_histS_Callback, h_fig}, ...
    'Position', [xNext yNext w_med_big h_edit]);

xNext = xNext + w_med_big;

h.optExpTr.edit_minS = uicontrol('Style', 'edit', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_hist, 'BackgroundColor', [1 1 1], ...
    'Position', [xNext yNext w_edit h_edit], 'Callback', ...
    {@edit_minS_Callback, h_fig});

xNext = xNext + mg/2 + w_edit;

h.optExpTr.edit_binS = uicontrol('Style', 'edit', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_hist, 'BackgroundColor', [1 1 1], ...
    'Position', [xNext yNext w_edit h_edit], 'Callback', ...
    {@edit_binS_Callback, h_fig});

xNext = xNext + mg/2 + w_edit;

h.optExpTr.edit_maxS = uicontrol('Style', 'edit', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_hist, 'BackgroundColor', [1 1 1], ...
    'Position', [xNext yNext w_edit h_edit], 'Callback', ...
    {@edit_maxS_Callback, h_fig});

xNext = mg;
yNext = yNext - mg - h_edit;

h.optExpTr.checkbox_histDiscr = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_hist, 'String', ...
    'save discretised histograms', 'Callback', ...
    {@checkbox_histDiscr_Callback, h_fig}, 'Position', ...
    [xNext yNext w_full_sub h_edit]);

xNext = mg;
yNext = yNext - mg - h_edit;

h.optExpTr.radiobutton_noHist = uicontrol('Style', 'radiobutton', ...
    'Units', 'pixels', 'Parent', h.optExpTr.uipanel_hist, 'String', ...
    'No histogram file', 'Position', ...
    [xNext yNext w_full_pan h_edit], 'Callback', ...
    {@radiobutton_noHist_Callback, h_fig});



%% panel export dwell-times

xNext = wPan + 2*mg;
yNext = hFig - 2*mg - h_txt - hPan_dt;

h.optExpTr.uipanel_dt = uipanel('Parent', h.optExpTr.figure_optExpTr, ...
    'Units', 'pixels', 'Title', 'Dwell-time files', 'Position', ...
    [xNext yNext wPan hPan_dt], 'FontWeight', 'bold');

xNext = mg;
yNext = hPan_dt - 2*mg - h_edit;

h.optExpTr.radiobutton_saveDt = uicontrol('Style', 'radiobutton', ...
    'Units', 'pixels', 'Parent', h.optExpTr.uipanel_dt, 'String', ...
    'Export dwell-times', 'Position', [xNext yNext w_full_pan h_edit], ...
    'Callback', {@radiobutton_saveDt_Callback, h_fig});

yNext = yNext - mg - h_txt;

h.optExpTr.text_dt2exp = uicontrol('Style', 'text', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_dt, 'String', ...
    'Dwell-times to export:', 'Position', ...
    [xNext yNext w_full_pan h_txt], 'HorizontalAlignment', 'left');

xNext = 2*mg;
yNext = yNext - mg - h_edit;

h.optExpTr.checkbox_dtI = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_dt, 'String', ...
    'intensities (*_I.dt)', 'Callback', ...
    {@checkbox_dtI_Callback, h_fig}, 'Position', ...
    [xNext yNext w_full_sub h_edit]);

yNext = yNext - mg/2 - h_edit;

h.optExpTr.checkbox_dtFRET = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_dt, 'String', ...
    'FRET (*_FRET.dt)', 'Callback', ...
    {@checkbox_dtFRET_Callback, h_fig}, 'Position', ...
    [xNext yNext w_full_sub h_edit]);

yNext = yNext - mg/2 - h_edit;

h.optExpTr.checkbox_dtS = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_dt, 'String', ...
    'stoichiometries (*_S.dt)', 'Callback', ...
    {@checkbox_dtS_Callback, h_fig}, 'Position', ...
    [xNext yNext w_full_sub h_edit]);

yNext = yNext - mg - h_edit;

h.optExpTr.checkbox_kin = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_dt, 'String', ...
    'generate kinetic data (*.kin)', 'Callback', ...
    {@checkbox_kin_Callback, h_fig}, 'Position', ...
    [xNext yNext w_full_sub h_edit]);

xNext = mg;
yNext = yNext - mg - h_edit;

h.optExpTr.radiobutton_noDt = uicontrol('Style', 'radiobutton', ...
    'Units', 'pixels', 'Parent', h.optExpTr.uipanel_dt, 'String', ...
    'No dwell-time file', 'Position', [xNext yNext w_full_pan h_edit], ...
    'Callback', {@radiobutton_noDt_Callback, h_fig});


%% panel export figures

xNext = wPan + 2*mg;
yNext = hFig - 3*mg - h_txt - hPan_dt - hPan_fig;

% modified by MH, 10.4.2019
h.optExpTr.uipanel_fig = uipanel('Parent', h.optExpTr.figure_optExpTr, ...
    'Units', 'pixels', 'Title','Figures', 'Position', ...
    [xNext yNext wPan hPan_fig], 'FontWeight','bold');
%     [xNext yNext wPan hPan_fig]);

xNext = mg;

% modified by MH, 10.4.2019
% yNext = hPan_tr - 3*mg - h_edit;
yNext = hPan_tr - 2*mg - h_edit;

h.optExpTr.radiobutton_saveFig = uicontrol('Style', 'radiobutton', ...
    'Units', 'pixels', 'Parent', h.optExpTr.uipanel_fig, 'String', ...
    'Export figures', 'Position', [xNext yNext w_full_pan h_edit], ...
    'Callback', {@radiobutton_saveFig_Callback, h_fig});

xNext = mg;
yNext = yNext - mg - h_edit;

h.optExpTr.text_figFmt = uicontrol('Style', 'text', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_fig, 'String', 'Export format:', ...
    'Position', [xNext yNext w_med h_txt], 'HorizontalAlignment', 'left');

xNext = xNext + w_med;

h.optExpTr.popupmenu_figFmt = uicontrol('Style', 'popupmenu', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_fig, 'String', str_figFmt, ...
    'Position', [xNext yNext w_pop h_edit], 'Callback', ...
    {@popupmenu_figFmt_Callback, h_fig}, 'BackgroundColor', [1 1 1]);

xNext = mg;

% added by MH, 10.4.2019
yNext = yNext - mg/2 - h_txt;
h.optExpTr.text_figInfos = uicontrol('Style', 'text', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_fig, 'UserData', str_figInfos, ...
    'Position', [xNext yNext w_full_pan h_txt], 'HorizontalAlignment', ...
    'left', 'ForegroundColor', [0 0 1]);

yNext = yNext - mg - h_edit;

h.optExpTr.text_nMol = uicontrol('Style', 'text', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_fig, 'String', ...
    'molecules per page:', 'Position', [xNext yNext w_big h_txt], ...
    'HorizontalAlignment', 'left');

xNext = xNext + w_big;

h.optExpTr.edit_nMol = uicontrol('Style', 'edit', 'Units', 'pixels', ...
    'Parent', h.optExpTr.uipanel_fig, 'BackgroundColor', [1 1 1], ...
    'Position', [xNext yNext w_edit h_edit], 'Callback', ...
    {@edit_nMol_Callback, h_fig});

xNext = mg;
yNext = yNext - mg - h_edit;

h.optExpTr.checkbox_subImg = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_fig, 'String', ...
    'molecule sub-images', 'Position', [xNext yNext w_full_pan h_edit], ...
    'Callback', {@checkbox_subImg_Callback, h_fig});

yNext = yNext - mg/2 - h_edit;

h.optExpTr.checkbox_top = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_fig, 'String', 'top axes:', ...
    'Callback', {@checkbox_top_Callback, h_fig}, 'Position', ...
    [xNext yNext w_med h_edit]);

xNext = xNext + w_med;

h.optExpTr.popupmenu_topExc = uicontrol('Style', 'popupmenu', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_fig, 'String', ...
    str_figTopExc, 'Position', [xNext yNext w_but h_edit], 'Callback', ...
    {@popupmenu_topExc_Callback, h_fig}, 'BackgroundColor', [1 1 1]);

xNext = xNext + mg/2 + w_but;

h.optExpTr.popupmenu_topChan = uicontrol('Style', 'popupmenu', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_fig, 'String', ...
    str_figTopChan, 'Position', [xNext yNext w_but h_edit], 'Callback', ...
    {@popupmenu_topChan_Callback, h_fig}, 'BackgroundColor', [1 1 1]);

xNext = mg;
yNext = yNext - mg/2 - h_edit;

h.optExpTr.checkbox_bottom = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_fig, 'String', ...
    'bottom axes:', 'Callback', {@checkbox_bottom_Callback, h_fig}, ...
    'Position', [xNext yNext w_med h_edit]);

xNext = xNext + w_med;

h.optExpTr.popupmenu_botChan = uicontrol('Style', 'popupmenu', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_fig, 'String', ...
    str_figBotChan, 'Position', [xNext yNext w_pop h_edit], 'Callback', ...
    {@popupmenu_botChan_Callback, h_fig}, 'BackgroundColor', [1 1 1]);

xNext = 2*mg;
yNext = yNext - mg/2 - h_edit;

h.optExpTr.checkbox_figHist = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_fig, 'String', ...
    'histogram axes', 'Callback', {@checkbox_figHist_Callback, h_fig}, ...
    'Position', [xNext yNext w_full_sub h_edit]);

xNext = 2*mg;
yNext = yNext - mg/2 - h_edit;

h.optExpTr.checkbox_figDiscr = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.uipanel_fig, 'String', ...
    'include disctretised traces', 'Position', [xNext yNext w_full_sub ...
    h_edit], 'Callback', {@checkbox_figDiscr_Callback, h_fig});

xNext = wPan - mg - w_but;
yNext = yNext - mg - h_but;

h.optExpTr.pushbutton_preview = uicontrol('Style', 'pushbutton', ...
    'Parent', h.optExpTr.uipanel_fig, 'Units', 'pixels', ...
    'Position', [xNext yNext w_but h_but], 'String', 'Preview', ...
    'Callback', {@pushbutton_preview_Callback, h_fig});

xNext = mg;
yNext = mg;

h.optExpTr.radiobutton_noFig = uicontrol('Style', 'radiobutton', ...
    'Units', 'pixels', 'Parent', h.optExpTr.uipanel_fig, 'String', ...
    'No figure file', 'Position', [xNext yNext w_full_pan h_edit], ...
    'Callback', {@radiobutton_noFig_Callback, h_fig});


%% Pushbuttons

xNext = 2*mg;
yNext = mg;

h.optExpTr.checkbox_molValid = uicontrol('Style', 'checkbox', 'Units', ...
    'pixels', 'Parent', h.optExpTr.figure_optExpTr, 'String', ...
    'save sel. mol. only', 'FontSize', 8, 'Callback', ...
    {@checkbox_molValid_Callback, h_fig}, 'Position', ...
    [xNext yNext w_full_pan h_but]);

% popup for exporting tagged molecules individually; 
% added by FS, 24.4.2018
xNext = mg + 2/3*w_full_pan;
str_lst = getStrPopTags(tagNames,tagClr);
molTagStr = [str_lst, 'all molecules'];
h.optExpTr.popup_molTagged = uicontrol('Style', 'popup', 'Units', ...
    'pixels', 'Parent', h.optExpTr.figure_optExpTr, 'String', molTagStr,...
    'Value', length(molTagStr), 'Callback', ...
    {@popup_molTagged_Callback, h_fig}, 'Position', ...
    [xNext yNext 1/2*w_full_pan h_but]);

% update parameter with current value
% added by MH, 08.02.2019
guidata(h_fig,h);
popup_molTagged_Callback(h.optExpTr.popup_molTagged, [], h_fig);
h = guidata(h_fig);

xNext = wFig - 3*w_but - 3*mg;
yNext = mg;
xNext = xNext + w_but + mg;

h.optExpTr.pushbutton_cancel = uicontrol('Style', 'pushbutton', ...
    'Parent', h.optExpTr.figure_optExpTr, 'Units', 'pixels', ...
    'Position', [xNext yNext w_but h_but], 'String', 'Cancel', ...
    'Callback', {@pushbutton_cancel_Callback, h_fig});

guidata(h_fig,h);
h.optExpTr.pushbutton_help = setInfoIcons(h.optExpTr.pushbutton_cancel,...
    h_fig,h.param.movPr.infos_icon_file);

xNext = xNext + w_but + mg;

h.optExpTr.pushbutton_next = uicontrol('Style', 'pushbutton', ...
    'Parent', h.optExpTr.figure_optExpTr, 'Units', 'pixels', ...
    'Position', [xNext yNext w_but h_but], 'String', 'Next >>', ...
    'Callback', {@pushbutton_next_Callback, h_fig});

guidata(h_fig, h);
ud_optExpTr('all', h_fig);


