function buildWinTrOpt(p, h_fig)
% buildWinTrOpt(p,h_fig)
%
% Build figure for ASCII trace import settings
%
% p: {1-by-6} import settings with:
%  p{1}: {1-by-2} intensity import options with:
%   p{1}{1}: [1-by-10] parameters of file structure
%    [1 0 0 1 1 0 nChan nExc 0 5]
%   p{1}{2}: [1-by-nL] laser wavelength in a chronological order
%
%     {0 ''} ...
%     {0 '' {[1 2] 1} 256} ...
%     [0 1] ...
%     defprm ...
%     {0 '' {} 0 '' {}}}
% h_fig: handle to main figure

% Last update, 28.3.2019 by MH: (1) Add "Gamma factor" panel (2) Add "State trajectories" panel (3) Change "Movie" to "Video" 

mg = 10;
h_txt = 14;
h_edit = 20; w_edit = 40;
h_but = 22; w_but_short = 22; w_but_med = 50; w_but_big = 98;
h_pop = 20; w_pop = 60;
h_cb = 20;
w_short = 30; w_med = 70; w_big = 90; w_full = 230;

h_pan_discr = 10 + h_cb + h_edit + 3*mg;
h_pan_fact = 10 + 2*h_cb + 2*h_but + 5*mg;
h_pan_int = 10 + 5*h_edit + h_pop + h_txt + 8*mg;
h_pan_mov = 10 + h_cb + h_but + 3*mg;
h_pan_coord = 10 + 2*h_but + 2*h_edit + 5*mg;

w_pan = w_full + 2*mg;
hFig = h_pan_int + h_pan_mov + h_pan_coord + h_but + 5*mg;
wFig = 2*w_pan + 3*mg;

pos_0 = get(0, 'ScreenSize');
xFig = pos_0(1) + (pos_0(3) - wFig)/2;
yFig = pos_0(2) + (pos_0(4) - hFig)/2;
if hFig > pos_0(4)
    yFig = yFig - (hFig-pos_0(4));
end

h = guidata(h_fig);

if ~(isfield(h, 'figure_trImpOpt') && ishandle(h.figure_trImpOpt))

    h.figure_trImpOpt = figure('Color', [0.94 0.94 0.94], 'Resize', ...
        'off', 'NumberTitle', 'off', 'MenuBar', 'none', 'Name', ...
        'Import ASCII options', 'Visible', 'off', 'Units', 'pixels', ...
        'Position', [xFig yFig wFig hFig], 'CloseRequestFcn', ...
        {@figure_trImpOpt_CloseRequestFcn, h_fig}, 'WindowStyle', 'Modal');
    guidata(h.figure_trImpOpt, p);

    
    bgCol = get(h.figure_trImpOpt, 'Color');

    yNext = mg;
    xNext = wFig - mg - w_but_med;

    h.trImpOpt.pushbutton_trImpOpt_ok = uicontrol('Style', ...
        'pushbutton', 'String', 'Save', 'Units', 'pixels', ...
        'BackgroundColor', bgCol, 'Position', ...
        [xNext yNext w_but_med h_but], 'Callback', ...
        {@pushbutton_trImpOpt_ok_Callback, h_fig});

    xNext = xNext - w_but_med - mg;

    h.trImpOpt.pushbutton_trImpOpt_cancel = uicontrol('Style', ...
        'pushbutton', 'String', 'Cancel', 'Units', 'pixels', ...
        'BackgroundColor', bgCol, 'Position', ...
        [xNext yNext w_but_med h_but], 'Callback', ...
        {@pushbutton_trImpOpt_cancel_Callback, h_fig});
    
    guidata(h_fig,h);
    h.trImpOpt.pushbutton_help = setInfoIcons(...
        h.trImpOpt.pushbutton_trImpOpt_cancel,h_fig,...
        h.param.movPr.infos_icon_file);

    yNext = yNext + h_but + mg;
    xNext = mg;

    h.trImpOpt.uipanel_ITT = uipanel('Title', 'Intensity-time traces', ...
        'Units', 'pixels', 'BackgroundColor', bgCol, 'FontWeight', ...
        'bold', 'Position', [xNext yNext w_pan h_pan_int]);
    
    yNext = yNext + h_pan_int + mg;
    
    h.trImpOpt.uipanel_mov = uipanel('Title', 'Single moelcule video', ...
        'Units', 'pixels', 'BackgroundColor', bgCol, 'FontWeight', 'bold', ...
        'Position', [xNext yNext w_pan h_pan_mov]);
     
    yNext = yNext + h_pan_mov + mg;
    
    h.trImpOpt.uipanel_coord = uipanel('Title', 'Molecule coordinates', ...
        'Units', 'pixels', 'BackgroundColor', bgCol, 'FontWeight', ...
        'bold', 'Position', [xNext yNext w_pan h_pan_coord]);
    
    xNext = xNext + w_pan + mg;
    yNext = hFig - mg - h_pan_fact - mg - h_pan_discr;
    
    h.trImpOpt.uipanel_discr = uipanel('Title', 'State trajectories', ...
        'Units', 'pixels', 'BackgroundColor', bgCol, 'FontWeight', 'bold', ...
        'Position', [xNext yNext w_pan h_pan_discr]);
    
    yNext = yNext + h_pan_discr + mg;
    
    h.trImpOpt.uipanel_factors = uipanel('Title', 'Correction factors', ...
        'Units', 'pixels', 'BackgroundColor', bgCol, 'FontWeight', 'bold', ...
        'Position', [xNext yNext w_pan h_pan_fact]);
   
    %% Coordinates panel
    
    if p{4}(1)
        enbl_ttfile = 'on';
    else
        enbl_ttfile = 'off';
    end
    if p{3}{1}
        enbl_extfile = 'on';
    else
        enbl_extfile = 'off';
    end
    
    if ~isempty(p{3}{2})
        [o,fname_coord,fext] = fileparts(p{3}{2});
        fname_coord = [fname_coord fext];
    else
        fname_coord = [];
    end

    yNext = mg;
    xNext = mg;
    
    h.trImpOpt.checkbox_inTTfile = uicontrol('Style', 'checkbox', ...
        'Parent', h.trImpOpt.uipanel_coord, 'String', ...
        'In traces file', 'Units', 'pixels', 'BackgroundColor', bgCol, ...
        'Position', [xNext yNext w_big h_cb], 'Callback', ...
        {@checkbox_inTTfile_Callback, h_fig}, 'Value', p{4}(1));
    
    xNext = xNext + w_big + mg;
    
    h.trImpOpt.text_rowCoord = uicontrol('Style', 'text', 'Parent', ...
        h.trImpOpt.uipanel_coord, 'String', 'row:', 'Units', ...
        'pixels', 'BackgroundColor', bgCol, 'HorizontalAlignment', ...
        'left', 'Position', [xNext yNext w_short h_txt], 'Enable', ...
        enbl_ttfile);

    xNext = xNext + w_short;

    h.trImpOpt.edit_rowCoord = uicontrol('Style', 'edit', 'Parent', ...
        h.trImpOpt.uipanel_coord, 'String', num2str(p{4}(2)), ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1], 'Position', ...
        [xNext yNext w_edit h_edit], 'Callback', ...
        {@edit_rowCoord_Callback, h_fig}, 'Enable', enbl_ttfile);

    yNext = yNext + h_cb + mg;
    xNext = mg;
    
    h.trImpOpt.text_movWidth = uicontrol('Style', 'text', 'String', ...
        'Movie width:', 'HorizontalAlignment', 'left', 'Parent', ...
        h.trImpOpt.uipanel_coord, 'BackgroundColor', bgCol, ...
        'Position', [xNext yNext w_med h_txt], 'Enable', enbl_extfile);
    
    xNext = xNext + w_med;
    
    h.trImpOpt.edit_movWidth = uicontrol('Style', 'edit', 'Parent', ...
        h.trImpOpt.uipanel_coord, 'String', num2str(p{3}{4}), ...
        'Callback', {@edit_movWidth_Callback, h_fig}, 'Position', ...
        [xNext yNext w_edit h_edit], 'BackgroundColor', [1 1 1], ...
        'Enable', enbl_extfile);
    
    yNext = yNext + h_edit + mg;
    xNext = mg;
    
    h.trImpOpt.pushbutton_impCoordFile = uicontrol('Style', ...
        'pushbutton', 'Parent', h.trImpOpt.uipanel_coord, ...
        'String', '...', 'Units', 'pixels', 'BackgroundColor', bgCol, ...
        'Position', [xNext yNext w_but_short h_but], 'Enable', ...
        enbl_extfile, 'Callback', {@pushbutton_impCoordFile_Callback, ...
        h_fig});

    xNext = xNext + w_but_short + mg;

    h.trImpOpt.text_fnameCoord = uicontrol('Style', 'text', 'Parent', ...
        h.trImpOpt.uipanel_coord, 'String', fname_coord, 'Units', ...
        'pixels', 'BackgroundColor', [1 1 1], 'ForegroundColor', ...
        [0 0 1], 'HorizontalAlignment', 'left', 'Enable', enbl_extfile, ...
        'Position', [xNext yNext w_full-mg-w_but_short h_txt]);

    yNext = yNext + h_but + mg;
    xNext = mg;

    h.trImpOpt.checkbox_extFile = uicontrol('Style', 'checkbox', ...
        'Parent', h.trImpOpt.uipanel_coord, 'String', ...
        'External file', 'Units', 'pixels', 'BackgroundColor', bgCol, ...
        'Position', [xNext yNext w_big h_cb], 'Callback', ...
        {@checkbox_extFile_Callback, h_fig}, 'Value', p{3}{1});

    xNext = xNext + w_big + mg;

    h.trImpOpt.pushbutton_impCoordOpt = uicontrol('Style', ...
        'pushbutton', 'Parent', h.trImpOpt.uipanel_coord, ...
        'String', 'Import options', 'Units', 'pixels', ...
        'BackgroundColor', bgCol, 'Position', ...
        [xNext yNext w_but_big h_but], 'Enable', enbl_extfile, ...
        'Callback', {@pushbutton_impCoordOpt_Callback, h_fig});

    
    %% Video panel
    
    if p{2}{1}
        enbl_movfile = 'on';
    else
        enbl_movfile = 'off';
    end

    if ~isempty(p{2}{2})
        [o,fname_mov,fext] = fileparts(p{2}{2});
        fname_mov = [fname_mov fext];
    else
        fname_mov = [];
    end
    
    yNext = mg;
    xNext = mg;

    h.trImpOpt.pushbutton_impMovFile = uicontrol('Style', ...
        'pushbutton', 'Parent', h.trImpOpt.uipanel_mov, ...
        'String', '...', 'Units', 'pixels', 'BackgroundColor', bgCol, ...
        'Position', [xNext yNext w_but_short h_but], 'Enable', ...
        enbl_movfile, 'Callback', {@pushbutton_impMovFile_Callback, ...
        h_fig});

    xNext = xNext + w_but_short + mg;

    h.trImpOpt.text_fnameMov = uicontrol('Style', 'text', 'Parent', ...
        h.trImpOpt.uipanel_mov, 'String', fname_mov, 'Units', ...
        'pixels', 'BackgroundColor', [1 1 1], 'ForegroundColor', ...
        [0 0 1], 'HorizontalAlignment', 'left', 'Enable', enbl_movfile, ...
        'Position', [xNext yNext w_full-mg-w_but_short h_txt]);
    
    yNext = yNext + h_but + mg;
    xNext = mg;
    
    h.trImpOpt.checkbox_impMov = uicontrol('Style', 'checkbox', ...
        'Parent', h.trImpOpt.uipanel_mov, 'String', ...
        'Video file', 'Units', 'pixels', 'BackgroundColor', bgCol, ...
        'Position', [xNext yNext w_full h_cb], 'Callback', ...
        {@checkbox_impMov_Callback, h_fig}, 'Value', p{2}{1});
    
    
    %% Intensity-time traces panel
    
    if p{1}{1}(3)
        enbl_coltime = 'on';
    else
        enbl_coltime = 'off';
    end
    
    yNext = mg;
    xNext = mg;
    
    uicontrol('Style', 'text', 'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', 'Wavelength:', 'HorizontalAlignment', 'left', ...
        'Position', [xNext yNext w_med h_txt]);
    
    xNext = xNext + w_med;
    
    str_pop = {};
    for i = 1:p{1}{1}(8)
        if i > numel(p{1}{2})
            p{1}{2}(i) = round(p{1}{2}(1)*(1 + 0.2*(i-1)));
        end
        str_pop = {str_pop{:} ['exc. ' num2str(i)]};
    end
    
    h.trImpOpt.popupmenu_exc = uicontrol('Style', 'popupmenu', ...
        'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', str_pop, 'Position', [xNext yNext w_pop h_pop], ...
        'Callback', {@popupmenu_exc_Callback, h_fig}, 'Value', 1, ...
        'BackgroundColor', [1 1 1]);
    
    xNext = xNext + w_pop + mg;
    
    h.trImpOpt.edit_wl = uicontrol('Style', 'edit', 'Parent', ...
        h.trImpOpt.uipanel_ITT, 'String', num2str(p{1}{2}(1)), ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1], 'Position', ...
        [xNext yNext w_edit h_edit], 'Callback', {@edit_wl_Callback, ...
        h_fig});
    
    xNext = xNext + w_edit;
    
    uicontrol('Style', 'text', 'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', 'nm', 'HorizontalAlignment', 'left', ...
        'Position', [xNext yNext w_short h_txt]);
    
    yNext = yNext + h_pop + mg;
    xNext = mg;
    
    uicontrol('Style', 'text', 'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', 'nb. of excitations:', 'HorizontalAlignment', 'left', ...
        'Position', [xNext yNext w_big h_txt]);

    xNext = xNext + w_big;
    
    h.trImpOpt.edit_nbExc = uicontrol('Style', 'edit', 'Parent', ...
        h.trImpOpt.uipanel_ITT, 'String', num2str(p{1}{1}(8)), ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1], 'Position', ...
        [xNext yNext w_edit h_edit], 'Callback', {@edit_nbExc_Callback, ...
        h_fig});

    xNext = xNext + w_edit + mg;
    
    uicontrol('Style', 'text', 'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', '(row-wise)', 'HorizontalAlignment', 'left', ...
        'Position', [xNext yNext w_big h_txt]);

    yNext = yNext + h_edit + mg;
    xNext = mg;
    
    uicontrol('Style', 'text', 'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', 'nb. of channels:', 'HorizontalAlignment', 'left', ...
        'Position', [xNext yNext w_big h_txt]);

    xNext = xNext + w_big;
    
    h.trImpOpt.edit_nbChan = uicontrol('Style', 'edit', 'Parent', ...
        h.trImpOpt.uipanel_ITT, 'String', num2str(p{1}{1}(7)), ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1], 'Position', ...
        [xNext yNext w_edit h_edit], 'Callback', ...
        {@edit_nbChan_Callback, h_fig});
    
    xNext = xNext + w_edit + mg;
    
    uicontrol('Style', 'text', 'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', '(column-wise)', 'HorizontalAlignment', 'left', ...
        'Position', [xNext yNext w_big h_txt]);
    
    yNext = yNext + h_edit + mg;
    xNext = mg;

    h.trImpOpt.checkbox_timeCol = uicontrol('Style', 'checkbox', ...
        'Parent', h.trImpOpt.uipanel_ITT, 'String', ...
        'Time data', 'Units', 'pixels', 'BackgroundColor', bgCol, ...
        'Position', [xNext yNext w_big h_cb], 'Callback', ...
        {@checkbox_timeCol_Callback, h_fig}, 'Value', p{1}{1}(3), ...
        'FontAngle', 'italic');
    
    xNext = xNext + w_big;
    
    h.trImpOpt.text_timeCol = uicontrol('Style', 'text', 'Parent', ...
        h.trImpOpt.uipanel_ITT, 'String', 'column:', ...
        'HorizontalAlignment', 'left', 'Position', ...
        [xNext yNext w_edit h_txt]);
    
    xNext = xNext + w_edit;
    
    h.trImpOpt.edit_timeCol = uicontrol('Style', 'edit', 'Parent', ...
        h.trImpOpt.uipanel_ITT, 'String', num2str(p{1}{1}(4)), ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1], 'Position', ...
        [xNext yNext w_edit h_edit], 'Callback', ...
        {@edit_timeCol_Callback, h_fig}, 'Enable', enbl_coltime);

    yNext = yNext + h_edit + mg;
    xNext = mg;
    
    uicontrol('Style', 'text', 'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', 'column:', 'HorizontalAlignment', 'left', ...
        'Position', [xNext yNext w_edit h_txt]);

    xNext = xNext + w_edit;
    
    h.trImpOpt.edit_startColI = uicontrol('Style', 'edit', 'Parent', ...
        h.trImpOpt.uipanel_ITT, 'String', num2str(p{1}{1}(5)), ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1], 'Position', ...
        [xNext yNext w_edit h_edit], 'Callback', ...
        {@edit_startColI_Callback, h_fig});
    
    xNext = xNext + w_edit;
    
    uicontrol('Style', 'text', 'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', 'to', 'HorizontalAlignment', 'center', ...
        'Position', [xNext yNext w_short h_txt]);
    
    xNext = xNext + w_short;
    
    h.trImpOpt.edit_stopColI = uicontrol('Style', 'edit', 'Parent', ...
        h.trImpOpt.uipanel_ITT, 'String', num2str(p{1}{1}(6)), ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1], 'Position', ...
        [xNext yNext w_edit h_edit], 'Callback', ...
        {@edit_stopColI_Callback, h_fig});

    xNext = xNext + w_edit + mg;

    uicontrol('Style', 'text', 'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', '(0 = end)', 'HorizontalAlignment', 'left', ...
        'Position', [xNext yNext w_full-2*(w_short+mg+w_edit) h_txt]);
    
    yNext = yNext + h_edit + mg;
    xNext = mg;
    
    uicontrol('Style', 'text', 'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', 'row:', 'HorizontalAlignment', 'left', ...
        'Position', [xNext yNext w_edit h_txt]);
    
    xNext = xNext + w_edit;
    
    h.trImpOpt.edit_startRow = uicontrol('Style', 'edit', 'Parent', ...
        h.trImpOpt.uipanel_ITT, 'String', num2str(p{1}{1}(1)), ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1], 'Position', ...
        [xNext yNext w_edit h_edit], 'Callback', ...
        {@edit_startRow_Callback, h_fig});
    
    xNext = xNext + w_edit;
    
    uicontrol('Style', 'text', 'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', 'to', 'HorizontalAlignment', 'center', ...
        'Position', [xNext yNext w_short h_txt]);
    
    xNext = xNext + w_short;
    
    h.trImpOpt.edit_stopRow = uicontrol('Style', 'edit', 'Parent', ...
        h.trImpOpt.uipanel_ITT, 'String', num2str(p{1}{1}(2)), ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1], 'Position', ...
        [xNext yNext w_edit h_edit], 'Callback', ...
        {@edit_stopRow_Callback, h_fig});
    
    xNext = xNext + w_edit + mg;
    
    uicontrol('Style', 'text', 'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', '(0 = end)', 'HorizontalAlignment', 'left', ...
        'Position', [xNext yNext w_med h_txt]);
    
    yNext = yNext + h_edit + mg;
    xNext = mg;
    
    uicontrol('Style', 'text', 'Parent', h.trImpOpt.uipanel_ITT, ...
        'String', 'Intensity data:', 'HorizontalAlignment', 'left', ...
        'Position', [xNext yNext w_full h_txt], 'FontAngle', 'italic');
    
    
    %% Factors panel
    
    if p{6}{1}
        enbl_gamfile = 'on';
    else
        enbl_gamfile = 'off';
    end
    if p{6}{4}
        enbl_betfile = 'on';
    else
        enbl_betfile = 'off';
    end
    str_gamfile = '';
    if ~isempty(p{6}{3})
        fname_gam = p{6}{3};
        for i = 1:numel(fname_gam)
            str_gamfile = cat(2,str_gamfile,fname_gam{i},'; ');
        end
        str_gamfile = str_gamfile(1:end-2);
    end
    str_betfile = '';
    if ~isempty(p{6}{6})
        fname_bet = p{6}{6};
        for i = 1:numel(fname_bet)
            str_betfile = cat(2,str_betfile,fname_bet{i},'; ');
        end
        str_betfile = str_betfile(1:end-2);
    end
    
    yNext = mg;
    xNext = mg;
    
    h.trImpOpt.pushbutton_impBetFile = uicontrol('Style', ...
        'pushbutton', 'Parent', h.trImpOpt.uipanel_factors, ...
        'String', '...', 'Units', 'pixels', 'BackgroundColor', bgCol, ...
        'Position', [xNext yNext w_but_short h_but], 'Enable', ...
        enbl_betfile, 'Callback', {@pushbutton_impBetFile_Callback, ...
        h_fig});

    xNext = xNext + w_but_short + mg;

    h.trImpOpt.text_fnameBet = uicontrol('Style', 'text', 'Parent', ...
        h.trImpOpt.uipanel_factors, 'String', str_betfile, 'Units', ...
        'pixels', 'BackgroundColor', [1 1 1], 'ForegroundColor', ...
        [0 0 1], 'HorizontalAlignment', 'left', 'Enable', enbl_betfile, ...
        'Position', [xNext yNext w_full-mg-w_but_short h_txt]);
    
    yNext = yNext + h_but + mg;
    xNext = mg;
    
    h.trImpOpt.checkbox_impBet = uicontrol('Style', 'checkbox', ...
        'Parent', h.trImpOpt.uipanel_factors, 'String', ...
        'Beta factors file', 'Units', 'pixels', 'BackgroundColor', bgCol, ...
        'Position', [xNext yNext w_full h_cb], 'Callback', ...
        {@checkbox_impBet_Callback, h_fig}, 'Value', p{6}{1});
    
    yNext = yNext + h_cb + mg;

    h.trImpOpt.pushbutton_impGamFile = uicontrol('Style', ...
        'pushbutton', 'Parent', h.trImpOpt.uipanel_factors, ...
        'String', '...', 'Units', 'pixels', 'BackgroundColor', bgCol, ...
        'Position', [xNext yNext w_but_short h_but], 'Enable', ...
        enbl_gamfile, 'Callback', {@pushbutton_impGamFile_Callback, ...
        h_fig});

    xNext = xNext + w_but_short + mg;

    h.trImpOpt.text_fnameGam = uicontrol('Style', 'text', 'Parent', ...
        h.trImpOpt.uipanel_factors, 'String', str_gamfile, 'Units', ...
        'pixels', 'BackgroundColor', [1 1 1], 'ForegroundColor', ...
        [0 0 1], 'HorizontalAlignment', 'left', 'Enable', enbl_gamfile, ...
        'Position', [xNext yNext w_full-mg-w_but_short h_txt]);
    
    yNext = yNext + h_but + mg;
    xNext = mg;
    
    h.trImpOpt.checkbox_impGam = uicontrol('Style', 'checkbox', ...
        'Parent', h.trImpOpt.uipanel_factors, 'String', ...
        'Gamma factors file', 'Units', 'pixels', 'BackgroundColor', bgCol, ...
        'Position', [xNext yNext w_full h_cb], 'Callback', ...
        {@checkbox_impGam_Callback, h_fig}, 'Value', p{6}{1});
    
    
    %% State trajectories panel
    
    if p{1}{1}(9)
        enbl_colFRET = 'on';
    else
        enbl_colFRET = 'off';
    end
    
    yNext = mg;
    xNext = mg;
    
    h.trImpOpt.text_every = uicontrol('Style', 'text', 'Parent', ...
        h.trImpOpt.uipanel_discr, 'String', 'every', ...
        'HorizontalAlignment', 'left', 'Position', ...
        [xNext yNext w_edit h_txt], 'Enable', enbl_colFRET);
    
    xNext = xNext + w_edit;
    
    h.trImpOpt.edit_thcol = uicontrol('Style', 'edit', 'Parent', ...
        h.trImpOpt.uipanel_discr, 'String', num2str(p{1}{1}(10)), ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1], 'Position', ...
        [xNext yNext w_edit h_edit], 'Callback', {@edit_thcol_Callback, ...
        h_fig}, 'Enable', enbl_colFRET);
    
    xNext = xNext + w_edit;
    
    h.trImpOpt.text_thcol = uicontrol('Style', 'text', 'Parent', ...
        h.trImpOpt.uipanel_discr, 'String', 'th column.', ...
        'HorizontalAlignment', 'left', 'Position', ...
        [xNext yNext w_med h_txt], 'Enable', enbl_colFRET);

    yNext = yNext + h_edit + mg;
    xNext = mg;
    
    h.trImpOpt.checkbox_dFRET = uicontrol('Style', 'checkbox', 'Parent',...
        h.trImpOpt.uipanel_discr, 'String', 'discretised FRET data', ...
        'Units', 'pixels', 'BackgroundColor', bgCol, ...
        'Position', [xNext yNext w_full h_cb], 'Callback', ...
        {@checkbox_dFRET_Callback, h_fig}, 'Value', p{1}{1}(9), ...
        'FontAngle', 'italic');
    
    guidata(h_fig, h);

    set(h.figure_trImpOpt, 'Visible', 'on');
end