function buildTraceManager(h_fig)

% Last update by MH, 24.8.2019
% >> solve issue in "View of video": video was shown upside down.
%
% update by MH, 24.4.2019
% >> add toolbar and empty tools "Auto sorting" and "View of video"
% >> rename "Overview" panel in "Molecule selection"
%
% update: by FS, 24.4.2018
% >> add debugging mode where all other windows are not deactivated
% >> add edit box to define a molecule tag
% >> add popup menu to select molecule tag
% >> add popup menu to select molecule tag
%
% update: by RB, 5.1.2018
% >> new pushbutton to inverse the selection of individual molecules
% >> add "to do" section: include y-axes control for FRET-S-Histogram
%
% update: by RB, 3.1.2018
% >> adapt width of popupmenu for FRET-S-Histogram 
%
% update: by RB, 15.12.2017
% >> update popupmenu_axes1 and popupmenu_axes2 string
%
%

%% build figure and toolbar

% defaults
defNperPage = 3; % molecules/ page
wFig = 900; hFig = 800; % figure dimensions
mg = 10; % margin
fntS = 10.6666666; % font size
fntS_big = 12; % font size
h_edit = 20; w_edit = 40; % edit field dimensions
h_but_big = 30; w_but_big = 120; % large pushbutton dimension
w_sld = 20; % slider bar x-dimension
w_cb = 200;
w_cb2 = 60;
h_cb = 20;
h_txt = 14; % text y-dimension
w_txt1 = 65; % medium text x-dimension
w_txt2 = 105; % large text x-dimension
w_txt3 = 32; % small text x-dimension

% pushbutton cdata
arrow_up = [0.92 0.92 0.92 0.92 0.92 0.92 0 0.92 0.92 0.92 0.92 0.92;
            0.92 0.92 0.92 1    1    0    0 0    0.92 0.92 0.92 0.92;
            0.92 0.92 1    1    0    0    0 0    0    0.92 0.92 0.92;
            0.92 1    1    0    0    0    0 0    0    0    0.92 0.92;
            1    1    0    0    0    0    0 0    0    0    0    0.85;
            1    0    0    0    0    0    0 0    0    0    0    0;
            1    1    1    1    1    1    1 1    1    1    1    0.85];

% get MASH figure dimensions
prev_u = get(h_fig, 'Units');
set(h_fig, 'Units', 'pixels');
posFig = get(h_fig, 'Position');
set(h_fig, 'Units', prev_u);
prev_u = get(0, 'Units');
set(0, 'Units', 'pixels');
pos_scr = get(0, 'ScreenSize');
set(0, 'Units', prev_u);

% set TM figure dimensions
xFig = posFig(1) + (posFig(3) - wFig)/2;
yFig = min([hFig pos_scr(4)]) - hFig;
pos_fig = [xFig yFig wFig hFig];

% set margins
mg_big = 2*mg;

% set UI control dimensions
h_pop = h_edit;
w_pop = 3*w_edit+2*mg/2;
h_but = h_edit;
w_but = (w_pop+w_txt3)/2;
w_edit2 = w_cb-w_cb2;

% set panels dimensions
w_pan = wFig - 2*mg;
h_pan_all = 5*mg + 2*h_pop + 2*h_edit + mg_big + h_but;
h_toolbar = h_but_big + 2*mg;
h_pan_sgl = hFig - 2*mg - h_pan_all - h_toolbar;
h_pan_tool = hFig - h_toolbar + mg;

% set axes dimensions
h_axes_all = h_pan_all - 2.5*mg;
w_axes_all = w_pan - w_txt3 - w_pop - 3*mg;
w_axes1 = (w_axes_all-2*mg)*0.75;
w_axes2 = w_axes_all - 2*mg - w_axes1;
w_axes4 = w_pan - w_cb - 3*mg;
h_axes4 = h_pan_tool -h_pop - 5*mg;

% adjust sliding bar dimensions
h_sld = h_pan_sgl - 3*mg - mg - h_but;

% fetch main figure's handles
h = guidata(h_fig);

% create TM figure
h.tm.figure_traceMngr = figure('Visible','on','Units','pixels','Position',...
    pos_fig,'Color',[0.94 0.94 0.94],'CloseRequestFcn',...
    {@figure_traceMngr_CloseRequestFcn, h_fig},'NumberTitle','off','Name',...
    ['Trace manager - ' get(h_fig, 'Name')],'MenuBar','none');

% add debugging mode where all other windows are not deactivated
% added by FS, 24.4.2018
debugMode = 1;
if ~debugMode
    set(h.tm.figure_traceMngr, 'WindowStyle', 'modal')
end

x_0 = mg;
y_0 = hFig;

xNext = x_0;
yNext = y_0 - mg - h_but_big;

h.tm.togglebutton_overview = uicontrol('style','togglebutton','parent',...
    h.tm.figure_traceMngr,'units','pixels','position',...
    [xNext,yNext,w_but_big,h_but_big],'string','Overview','fontweight',...
    'bold','fontunits','pixels','fontsize',fntS_big,'callback',...
    {@switchPan_TM,h_fig});

xNext = xNext + w_but_big + mg;

h.tm.togglebutton_autoSorting = uicontrol('style','togglebutton',...
    'parent',h.tm.figure_traceMngr,'units','pixels','position',...
    [xNext,yNext,w_but_big,h_but_big],'string','Auto sorting',...
    'fontweight','bold','fontunits','pixels','fontsize',fntS_big,...
    'callback',{@switchPan_TM,h_fig});

xNext = xNext + w_but_big + mg;

h.tm.togglebutton_videoView = uicontrol('style','togglebutton','parent',...
    h.tm.figure_traceMngr,'units','pixels','position',...
    [xNext,yNext,w_but_big,h_but_big],'string','View on video',...
    'fontweight','bold','fontunits','pixels','fontsize',fntS_big,...
    'callback',{@switchPan_TM,h_fig});

guidata(h_fig,h);
h.tm.pushbutton_help = setInfoIcons(h.tm.togglebutton_videoView,...
    h_fig,h.param.movPr.infos_icon_file);


%% build main panels

xNext = mg;
yNext = yNext - mg - h_pan_all;

h.tm.uipanel_overall = uipanel('Parent', h.tm.figure_traceMngr, ...
    'Units', 'pixels', 'Position', [xNext yNext w_pan h_pan_all], ...
    'Title', 'Overall plots', 'FontUnits', 'pixels', 'FontSize', fntS);

yNext = yNext - mg - h_pan_sgl;

h.tm.uipanel_overview = uipanel('Parent', h.tm.figure_traceMngr, ...
    'Units', 'pixels', 'Position', [xNext yNext w_pan h_pan_sgl], ...
    'Title','Molecule selection','FontUnits','pixels','FontSize',fntS);

xNext = -mg;
yNext = y_0 - mg - h_but_big - mg - h_pan_tool;

h.tm.uipanel_autoSorting = uipanel('Parent', h.tm.figure_traceMngr, ...
    'Units', 'pixels', 'Position', [xNext yNext wFig+2*mg h_pan_tool], ...
    'Title', '', 'FontUnits', 'pixels', ...
    'FontSize', fntS, 'Visible', 'off');

h.tm.uipanel_videoView = uipanel('Parent', h.tm.figure_traceMngr, ...
    'Units', 'pixels', 'Position', [xNext yNext wFig+2*mg h_pan_tool], ...
    'Title', '', 'FontUnits', 'pixels', ...
    'FontSize', fntS, 'Visible', 'off');


%% build panel overall plots

xNext = mg;
yNext = h_pan_all - 1.5*mg - h_pop;

h.tm.text1 = uicontrol('Style','text','Parent',h.tm.uipanel_overall,...
    'Units','pixels','String','plot1:','HorizontalAlignment','center',...
    'Position',[xNext yNext w_txt3 h_txt],'FontUnits','pixels','FontSize',...
    fntS,'FontWeight','bold');

xNext = xNext + w_txt3 + mg;

% RB 2017-12-15: update str_plot
str_plot = getStrPlot_overall(h_fig); % added by MH, 25.4.2019
h.tm.popupmenu_axes1 = uicontrol('Style','popupmenu','Parent', ...
    h.tm.uipanel_overall,'String',str_plot{1},'Units','pixels','Position',...
    [xNext yNext w_pop h_pop],'BackgroundColor',[1 1 1],'Callback',...
    {@popupmenu_axes_Callback, h_fig},'FontUnits','pixels','FontSize',...
    fntS);

xNext = mg;
yNext = yNext - mg - h_pop;

h.tm.text2 = uicontrol('Style','text','Parent',h.tm.uipanel_overall,...
    'Units','pixels','String','plot2:','HorizontalAlignment','center',...
    'Position',[xNext yNext w_txt3 h_txt],'FontUnits','pixels',...
    'FontSize',fntS,'FontWeight','bold');

xNext = xNext + w_txt3 + mg;

% RB 2017-12-15: update str_plot 
h.tm.popupmenu_axes2 = uicontrol('Style', 'popupmenu', 'Parent', ...
    h.tm.uipanel_overall, 'Units', 'pixels', 'String', str_plot{2}, ...
    'Position', [xNext yNext w_pop h_pop], 'BackgroundColor', ...
    [1 1 1], 'Callback', {@popupmenu_axes_Callback, h_fig}, ...
    'FontUnits', 'pixels', 'FontSize', fntS);

xNext = mg;
yNext = yNext - mg - h_edit;

h.tm.text3 = uicontrol('Style','text','Parent',h.tm.uipanel_overall,...
    'Units','pixels','String','xbins:','HorizontalAlignment','center',...
    'Position',[xNext yNext w_txt3 h_txt],'FontUnits','pixels','FontSize',...
    fntS);

xNext = xNext + w_txt3 + mg;

h.tm.edit_xlim_low = uicontrol('Style', 'edit', 'Parent', ...
    h.tm.uipanel_overall, 'Position', [xNext yNext w_edit h_edit], ...
    'Callback', {@edit_lim_low_Callback,h_fig,1}, 'String', '0', ...
    'BackgroundColor', [1 1 1], 'TooltipString', ...
    'lower interval value');

xNext = xNext + mg/2 + w_edit;

h.tm.edit_xnbiv = uicontrol('Style', 'edit', 'Parent', ...
    h.tm.uipanel_overall, 'Position', [xNext yNext w_edit h_edit], ...
    'Callback', {@edit_nbiv_Callback, h_fig,1}, 'String', '200', ...
    'BackgroundColor', [1 1 1], 'TooltipString', 'number of interval');

xNext = xNext + mg/2 + w_edit;

h.tm.edit_xlim_up = uicontrol('Style','edit','Parent',h.tm.uipanel_overall,...
    'Position', [xNext yNext w_edit h_edit],'Callback',...
    {@edit_lim_up_Callback,h_fig,1},'String','1','BackgroundColor',[1 1 1],...
    'TooltipString','upper interval value');

xNext = mg;
yNext = yNext - mg/2 - h_edit;

h.tm.text4 = uicontrol('Style','text','Parent',h.tm.uipanel_overall,...
    'Units','pixels','String','ybins:','HorizontalAlignment','center',...
    'Position',[xNext yNext w_txt3 h_txt],'FontUnits','pixels','FontSize',...
    fntS,'Enable','off');

xNext = xNext + w_txt3 + mg;

h.tm.edit_ylim_low = uicontrol('Style','edit','Parent',...
    h.tm.uipanel_overall,'Position',[xNext yNext w_edit h_edit],'Callback',...
    {@edit_lim_low_Callback,h_fig,2},'String','','BackgroundColor',[1 1 1],...
    'TooltipString','lower interval value','Enable','off');

xNext = xNext + mg/2 + w_edit;

h.tm.edit_ynbiv = uicontrol('Style','edit','Parent',h.tm.uipanel_overall,...
    'Position',[xNext yNext w_edit h_edit],'Callback',...
    {@edit_nbiv_Callback,h_fig,2},'String','','BackgroundColor',[1 1 1],...
    'TooltipString','number of interval','Enable','off');

xNext = xNext + mg/2 + w_edit;

h.tm.edit_ylim_up = uicontrol('Style','edit','Parent',h.tm.uipanel_overall,...
    'Position',[xNext yNext w_edit h_edit],'Callback',...
    {@edit_lim_up_Callback,h_fig,2},'String','','BackgroundColor',[1 1 1],...
    'TooltipString','upper interval value','Enable','off');

xNext = mg;
yNext = yNext - mg_big - h_but;

h.tm.pushbutton_update = uicontrol('Style', 'pushbutton', 'Parent', ...
    h.tm.uipanel_overall, 'Units', 'pixels', 'Position', ...
    [xNext yNext w_but h_but], 'String', 'UPDATE', 'TooltipString', ...
    'Update the graphs with new parameters', 'Callback', ...
    {@pushbutton_update_Callback, h_fig}, 'FontUnits', 'pixels', ...
    'FontSize', fntS);

xNext = xNext + mg + w_but;

h.tm.pushbutton_export = uicontrol('Style', 'pushbutton', 'Parent', ...
    h.tm.uipanel_overall, 'Units', 'pixels','FontWeight', 'bold', ...
    'String', 'TO MASH', 'Position', [xNext yNext w_but h_but], ...
    'TooltipString', 'Export selection to MASH', 'Callback', ...
    {@menu_export_Callback, h_fig}, 'FontUnits', 'pixels', ...
    'FontSize', fntS);

xNext = mg + w_txt3 + mg + w_pop + mg;
yNext = mg;

h.tm.axes_ovrAll_1 = axes('Parent',h.tm.uipanel_overall,'Units','pixels',...
    'FontUnits','pixels','FontSize',fntS,'ActivePositionProperty',...
    'OuterPosition','GridLineStyle',':','NextPlot','replacechildren',...
    'ButtonDownFcn',{@axes_ovrAll_1_ButtonDownFcn,h_fig});
ylim(h.tm.axes_ovrAll_1,[0 10000]);
pos = getRealPosAxes([xNext yNext w_axes1 h_axes_all], ...
    get(h.tm.axes_ovrAll_1,'TightInset'),'traces');
pos(3:4) = pos(3:4) - fntS;
pos(1:2) = pos(1:2) + fntS;
set(h.tm.axes_ovrAll_1,'Position',pos);

xNext = xNext + mg + w_axes1;
yNext = mg;

h.tm.axes_ovrAll_2 = axes('Parent', h.tm.uipanel_overall, 'Units', ...
    'pixels', 'FontUnits', 'pixels', 'FontSize', fntS, ...
    'ActivePositionProperty', 'OuterPosition', 'GridLineStyle', ':',...
    'NextPlot', 'replacechildren');
ylim(h.tm.axes_ovrAll_2,[0 10000]);
pos1 = pos;
pos = getRealPosAxes([xNext yNext w_axes2 h_axes_all], ...
    get(h.tm.axes_ovrAll_2, 'TightInset'), 'traces'); 
pos([2 4]) = pos1([2 4]);
pos(3) = pos(3) - fntS;
pos(1) = pos(1) + fntS;
set(h.tm.axes_ovrAll_2, 'Position', pos);


%% build panel molecule selection

xNext = mg;
yNext = h_pan_sgl - mg - mg - h_but + (h_but-h_txt)/2;
    
% added by MH, 24.4.2019
h.tm.text_selection = uicontrol('style','text','parent',...
    h.tm.uipanel_overview,'units','pixels','string','Selection:',...
    'position',[xNext,yNext,0.5*w_pop,h_txt],'fontunits','pixels', ...
    'fontsize', fntS,'fontweight','bold');

xNext = xNext + 0.5*w_pop + mg/2 ;
yNext = yNext - (h_but-h_txt)/2;

% added by MH, 24.4.2019
str_pop = getStrPop_select(h_fig);
h.tm.popupmenu_selection = uicontrol('style','popupmenu','parent',...
    h.tm.uipanel_overview,'units','pixels','string',str_pop,'value',1,...
    'position',[xNext,yNext,4/5*w_pop,h_but],'fontunits','pixels', ...
    'fontsize', fntS,'callback',{@popupmenu_selection_Callback,h_fig});

xNext = xNext + 4/5*w_pop + 2*mg;

h.tm.pushbutton_untagAll = uicontrol('style','pushbutton','parent', ...
    h.tm.uipanel_overview,'units','pixels','string','Untag all', ...
    'position',[xNext yNext 0.5*w_pop h_but],'tooltipString',...
    'Remove tags to all molecules','fontunits','pixels','fontsize',fntS,...
    'callback',{@pushbutton_untagAll_Callback,h_fig});

xNext = xNext + 0.5*w_pop + mg;

% edit box to define a molecule tag, added by FS, 24.4.2018
h.tm.edit_molTag = uicontrol('Style','edit','Parent',h.tm.uipanel_overview,...
    'Units','pixels','String','define a new tag','Position',...
    [xNext yNext w_pop h_but],'Callback',{@edit_addMolTag_Callback, h_fig}, ...
    'FontUnits','pixels','FontSize',fntS);

xNext = xNext + w_pop + mg;

% popup menu to select molecule tag, added by FS, 24.4.2018
% add callback, MH 24.4.2019
str_lst = colorTagNames(h_fig);
h.tm.popup_molTag = uicontrol('Style', 'popup', 'Parent', ...
    h.tm.uipanel_overview, 'Units', 'pixels', ...
    'String', str_lst, ...
    'Position', [xNext yNext w_pop h_but], ...
    'TooltipString', 'select a molecule tag', ...
    'FontUnits', 'pixels', ...
    'FontSize', fntS, 'Callback', {@popup_molTag_Callback,h_fig});

xNext = xNext + w_pop + mg;

% added by MH, 24.4.2019
h.tm.pushbutton_tagClr = uicontrol('style','pushbutton','parent', ...
    h.tm.uipanel_overview,'units','pixels','string','Set', ...
    'position',[xNext yNext w_edit h_but],'tooltipstring', ...
    'define the tag color','fontunits','pixels','fontsize',fntS,...
    'callback',{@pushbutton_tagClr_Callback,h_fig},'enable','off');

xNext = xNext + w_edit + mg;

% popup menu to select molecule tag, added by FS, 24.4.2018
h.tm.pushbutton_deleteMolTag = uicontrol('Style', 'pushbutton', 'Parent', ...
    h.tm.uipanel_overview, 'Units', 'pixels', ...
    'String', 'Delete tag', ...
    'Position', [xNext yNext 1/2*w_pop h_but], ...
    'TooltipString', 'Delete a default tag', ...
    'Callback', {@pushbutton_deleteMolTag_Callback, h_fig}, ...    
    'FontUnits', 'pixels', ...
    'FontSize', fntS);

xNext = w_pan - mg - w_but;

arrow_up = cat(3,arrow_up,arrow_up,arrow_up);
h.tm.pushbutton_reduce = uicontrol('Style', 'pushbutton', 'Parent', ...
    h.tm.uipanel_overview, 'Units', 'pixels', 'Position', ...
    [xNext yNext w_but h_but], 'CData', arrow_up, 'TooltipString', ...
    'Hide overall panel', 'Callback', ...
    {@pushbutton_reduce_Callback, h_fig});

xNext = xNext - mg_big - w_edit;

h.tm.edit_nbTotMol = uicontrol('Style','edit','Parent',...
    h.tm.uipanel_overview,'Units','pixels','Position',...
    [xNext yNext w_edit h_edit],'String',num2str(defNperPage),...
    'TooltipString','Number of molecule per view','BackgroundColor',...
    [1 1 1],'Callback',{@edit_nbTotMol_Callback, h_fig});

xNext = xNext - mg - w_edit;
yNext = yNext + (h_edit-h_txt)/2;

h.tm.textNmol = uicontrol('Style','text','Parent',h.tm.uipanel_overview,...
    'Units','pixels','String','disp:','HorizontalAlignment','right',...
    'Position',[xNext yNext w_edit h_txt],'FontUnits','pixels','FontSize',...
    fntS);

xNext = w_pan - mg - w_sld;
yNext = mg;

% define the number of molecule displayed per page
nb_mol = numel(h.tm.molValid);
if nb_mol < defNperPage
    nb_mol_disp = nb_mol;
else
    nb_mol_disp = defNperPage;
end
% adjust sliding parameters and visibility
if nb_mol <= nb_mol_disp || nb_mol_disp == 0
    min_step = 1;
    maj_step = 1;
    min_val = 0;
    max_val = 1;
    vis = 'off';
else
    vis = 'on';
    min_val = 1;
    max_val = nb_mol-nb_mol_disp+1;
    min_step = 1/(nb_mol-nb_mol_disp);
    maj_step = nb_mol_disp/(nb_mol-nb_mol_disp);
end
h.tm.slider = uicontrol('Style', 'slider', 'Parent', ...
    h.tm.uipanel_overview, 'Units', 'pixels', 'Position', ...
    [xNext yNext w_sld h_sld], 'Value', max_val, 'Max', max_val, ...
    'Min', min_val, 'Callback', {@slider_Callback, h_fig}, ...
    'SliderStep', [min_step maj_step], 'Visible', vis);

% save controls
guidata(h_fig, h);

% build controls and axes in panel "Molecule selection"
updatePanel_single(h_fig, nb_mol_disp);

% recover new controls
h = guidata(h_fig);
    
    
%% build panel auto-sorting

w_pan_slct = 0.5*w_pop + 2*w_edit + w_txt3 + 2.5*mg;
h_pan_slct = h_pan_tool-h_pop-h_txt-4*mg;
w_axes3 = wFig - w_pan_slct - 3*mg;
h_axes3a = (h_pan_slct-mg)*0.8;
h_axes3b = h_pan_slct-mg-h_axes3a;
w_lst = w_pan_slct-2*mg;
h_lst = 3*h_txt + 2*h_edit + 1.5*mg;

xNext = 2*mg;
yNext = 2*mg;

h.tm.uipanel_range = uipanel('parent',h.tm.uipanel_autoSorting, ...
    'units','pixels','position',[xNext yNext w_pan_slct h_pan_slct], ...
    'title','Ranges','fontunits','pixels','fontsize',fntS);

xNext = xNext + w_pan_slct + mg;

h.tm.axes_traceSort = axes('parent',h.tm.uipanel_autoSorting,...
    'units','pixels','fontunits','pixels','fontsize',fntS,...
    'activepositionproperty','outerposition','gridlineStyle',':',...
    'nextPlot','replacechildren');
ylim(h.tm.axes_traceSort,[0 10000]);
ylabel(h.tm.axes_traceSort,'counts per s. per pix.');
xlabel(h.tm.axes_traceSort,'time (s)');
t = title(h.tm.axes_traceSort,cat(2,'concatenated traces for molecule ',...
    'selection at last update'),'units','pixels');
pos = getRealPosAxes([xNext,yNext,w_axes3,h_axes3b], ...
get(h.tm.axes_traceSort,'TightInset'),'traces'); 
pos(3) = pos(3) - fntS;
pos(1) = pos(1) + fntS;
set(h.tm.axes_traceSort,'Position',pos);
pos_t = get(t,'extent');
set(t,'position',[(pos_t(3)+pos(3)-pos_t(3)-w_pop)/2,pos_t(2)]);

yNext = pos(2) + pos(4) + mg/2;
xNext = pos(1) + pos(3) - w_pop;

str_plot = getStrPlot_overall(h_fig);
h.tm.popupmenu_AS_plot1 = uicontrol('style','popupmenu','parent', ...
    h.tm.uipanel_autoSorting,'string',str_plot{1},'units','pixels',...
    'position',[xNext yNext w_pop h_pop],'backgroundcolor',[1 1 1],...
    'callback',{@popupmenu_axes_Callback,h_fig},'fontunits','pixels',...
    'fontsize',fntS);

xNext = w_pan_slct + 3*mg;
yNext = h_axes3b + 3*mg;

h.tm.axes_histSort = axes('parent',h.tm.uipanel_autoSorting,...
    'units','pixels','fontunits','pixels','fontsize',fntS,...
    'activepositionproperty','outerposition','gridlineStyle',':',...
    'nextPlot','replacechildren','buttondownfcn',...
    {@axes_histSort_ButtonDownFcn,h_fig});
ylim(h.tm.axes_histSort,[0 10000]);
ylabel(h.tm.axes_histSort,'freq. counts');
xlabel(h.tm.axes_histSort,'counts per s. per pix.');
title(h.tm.axes_histSort,...
    '1D-histogram for molecule selection at last update');
pos = getRealPosAxes([xNext,yNext,w_axes3,h_axes3a], ...
get(h.tm.axes_histSort,'TightInset'),'traces'); 
pos(3) = pos(3) - fntS;
pos(1) = pos(1) + fntS;
set(h.tm.axes_histSort,'Position',pos);

xNext = 2*mg;
yNext = yNext + h_axes3a + mg;

h.tm.text_selectData = uicontrol('style','text','parent',...
    h.tm.uipanel_autoSorting,'string','Select data:','position',...
    [xNext,yNext,w_txt1,h_txt],'fontunits','pixels','fontsize',fntS,...
    'fontweight','bold','horizontalalignment','left');

xNext = xNext + w_txt1 + mg;

str_pop = getStrPlot_overall(h_fig);
h.tm.popupmenu_selectData = uicontrol('style','popupmenu','parent',...
    h.tm.uipanel_autoSorting,'string',str_pop{2},'tooltipstring',...
    'Select the data to histogram','position',[xNext,yNext,w_pop,h_pop],...
    'fontunits','pixels','fontsize',fntS,'callback',...
    {@popupmenu_selectData_Callback,h_fig});
 
xNext = xNext + w_pop + 2*mg;

h.tm.text_selectCalc = uicontrol('style','text','parent',...
    h.tm.uipanel_autoSorting,'string','Select calculation:','position',...
    [xNext,yNext,w_txt2,h_txt],'fontunits','pixels','fontsize',fntS,...
    'fontweight','bold','horizontalalignment','left');
 
xNext = xNext + w_txt2 + mg;
 
str_pop = {'original time traces','means','minima','maxima','medians',...
    'state trajectories'};
h.tm.popupmenu_selectCalc = uicontrol('style','popupmenu','parent',...
    h.tm.uipanel_autoSorting,'string',str_pop,'tooltipstring',...
    'Select the calculated value to histogram','position',...
    [xNext,yNext,w_pop,h_pop],'fontunits','pixels','fontsize',fntS,...
    'callback',{@popupmenu_selectData_Callback,h_fig},'userdata',1);

xNext = xNext + w_pop + 2*mg;

h.tm.text_histogram = uicontrol('style','text','parent',...
    h.tm.uipanel_autoSorting,'string','Histogram:','position',...
    [xNext,yNext,w_txt1,h_txt],'fontunits','pixels','fontsize',fntS,...
    'fontweight','bold','horizontalalignment','left');

xNext = xNext + w_txt1 + mg;

h.tm.edit_xlow = uicontrol('style','edit','parent',...
    h.tm.uipanel_autoSorting,'string','','tooltipstring',...
    'Lower bound of x-axis','position',[xNext,yNext,w_edit,h_edit],...
    'fontunits','pixels','fontsize',fntS,'callback',...
    {@edit_xlow_Callback,h_fig});

yNext = yNext + h_edit;

h.tm.text_xlow = uicontrol('style','text','parent',...
    h.tm.uipanel_autoSorting,'string','x min','position',...
    [xNext,yNext,w_edit,h_txt],'fontunits','pixels','fontsize',fntS,...
    'horizontalalignment','center');

xNext = xNext + w_edit + mg/5;
yNext = yNext - h_edit;

h.tm.edit_xup = uicontrol('style','edit','parent',...
    h.tm.uipanel_autoSorting,'string','','tooltipstring',...
    'Upper bound of x-axis','position',[xNext,yNext,w_edit,h_edit],...
    'fontunits','pixels','fontsize',fntS,'callback',...
    {@edit_xup_Callback,h_fig});

yNext = yNext + h_edit;

h.tm.text_xup = uicontrol('style','text','parent',...
    h.tm.uipanel_autoSorting,'string','x max','position',...
    [xNext,yNext,w_edit,h_txt],'fontunits','pixels','fontsize',fntS,...
    'horizontalalignment','center');

xNext = xNext + w_edit + mg/5;
yNext = yNext - h_edit;

h.tm.edit_xniv = uicontrol('style','edit','parent',...
    h.tm.uipanel_autoSorting,'string','','tooltipstring',...
    'Number of binning intervals in x-axis','position',...
    [xNext,yNext,w_edit,h_edit],'fontunits','pixels','fontsize',fntS,...
    'callback',{@edit_xniv_Callback,h_fig});

yNext = yNext + h_edit;

h.tm.text_xniv = uicontrol('style','text','parent',...
    h.tm.uipanel_autoSorting,'string','nbins','position',...
    [xNext,yNext,w_edit,h_txt],'fontunits','pixels','fontsize',fntS,...
    'horizontalalignment','center');

xNext = xNext + w_edit + mg;
yNext = yNext - h_edit;

h.tm.edit_ylow = uicontrol('style','edit','parent',...
    h.tm.uipanel_autoSorting,'string','','tooltipstring',...
    'Lower bound of y-axis','position',[xNext,yNext,w_edit,h_edit],...
    'fontunits','pixels','fontsize',fntS,'callback',...
    {@edit_ylow_Callback,h_fig},'enable','off');

yNext = yNext + h_edit;

h.tm.text_ylow = uicontrol('style','text','parent',...
    h.tm.uipanel_autoSorting,'string','y min','position',...
    [xNext,yNext,w_edit,h_txt],'fontunits','pixels','fontsize',fntS,...
    'horizontalalignment','center','enable','off');

xNext = xNext + w_edit + mg/5;
yNext = yNext - h_edit;

h.tm.edit_yup = uicontrol('style','edit','parent',...
    h.tm.uipanel_autoSorting,'string','','tooltipstring',...
    'Upper bound of y-axis','position',[xNext,yNext,w_edit,h_edit],...
    'fontunits','pixels','fontsize',fntS,'callback',...
    {@edit_yup_Callback,h_fig},'enable','off');

yNext = yNext + h_edit;

h.tm.text_yup = uicontrol('style','text','parent',...
    h.tm.uipanel_autoSorting,'string','y max','position',...
    [xNext,yNext,w_edit,h_txt],'fontunits','pixels','fontsize',fntS,...
    'horizontalalignment','center','enable','off');

xNext = xNext + w_edit + mg/5;
yNext = yNext - h_edit;

h.tm.edit_yniv = uicontrol('style','edit','parent',...
    h.tm.uipanel_autoSorting,'string','','tooltipstring',...
    'Number of binning intervals in y-axis','position',...
    [xNext,yNext,w_edit,h_edit],'fontunits','pixels','fontsize',fntS,...
    'callback',{@edit_yniv_Callback,h_fig},'enable','off');

yNext = yNext + h_edit;

h.tm.text_yniv = uicontrol('style','text','parent',...
    h.tm.uipanel_autoSorting,'string','nbins','position',...
    [xNext,yNext,w_edit,h_txt],'fontunits','pixels','fontsize',fntS,...
    'horizontalalignment','center','enable','off');

    
%% build panel ranges

xNext = mg;
yNext = h_pan_slct - 1.5*mg - h_txt;

h.tm.text5 = uicontrol('style','text','parent',h.tm.uipanel_range,...
    'string','Range bounds:','position',[xNext,yNext,2*w_edit+mg/2,h_txt],...
    'fontunits','pixels','fontsize',fntS,'horizontalalignment','left',...
    'fontweight','bold');

yNext = yNext - mg - h_txt - h_edit;

h.tm.edit_xrangeLow = uicontrol('style','edit','parent',...
    h.tm.uipanel_range,'string','0','position',...
    [xNext,yNext,w_edit,h_edit],'fontunits','pixels','fontsize',fntS,...
    'callback',{@edit_xrangeLow_Callback,h_fig});

yNext = yNext + h_edit;

h.tm.text_xrangeLow = uicontrol('style','text','parent',...
    h.tm.uipanel_range,'string','xlow','position',...
    [xNext,yNext,w_edit,h_txt],'fontunits','pixels','fontsize',fntS,...
    'horizontalalignment','center');

yNext = yNext - h_edit;
xNext = xNext + w_edit + mg/2;

h.tm.edit_xrangeUp = uicontrol('style','edit','parent',...
    h.tm.uipanel_range,'string','1','position',...
    [xNext,yNext,w_edit,h_edit],'fontunits','pixels','fontsize',fntS,...
    'callback',{@edit_xrangeUp_Callback,h_fig});

yNext = yNext + h_edit;

h.tm.text_xrangeUp = uicontrol('style','text','parent',...
    h.tm.uipanel_range,'string','xup','position',...
    [xNext,yNext,w_edit,h_txt],'fontunits','pixels','fontsize',fntS,...
    'horizontalalignment','center');

yNext = yNext - h_edit;
xNext = xNext + w_edit + mg;

h.tm.edit_yrangeLow = uicontrol('style','edit','parent',...
    h.tm.uipanel_range,'string','0','position',...
    [xNext,yNext,w_edit,h_edit],'fontunits','pixels','fontsize',fntS,...
    'callback',{@edit_yrangeLow_Callback,h_fig},'enable','off');

yNext = yNext + h_edit;

h.tm.text_yrangeLow = uicontrol('style','text','parent',...
    h.tm.uipanel_range,'string','ylow','position',...
    [xNext,yNext,w_edit,h_txt],'fontunits','pixels','fontsize',fntS,...
    'horizontalalignment','center','enable','off');

yNext = yNext - h_edit;
xNext = xNext + w_edit + mg/2;

h.tm.edit_yrangeUp = uicontrol('style','edit','parent',...
    h.tm.uipanel_range,'string','1','position',...
    [xNext,yNext,w_edit,h_edit],'fontunits','pixels','fontsize',fntS,...
    'callback',{@edit_yrangeUp_Callback,h_fig},'enable','off');

yNext = yNext + h_edit;

h.tm.text_yrangeUp = uicontrol('style','text','parent',...
    h.tm.uipanel_range,'string','yup','position',...
    [xNext,yNext,w_edit,h_txt],'fontunits','pixels','fontsize',fntS,...
    'horizontalalignment','center','enable','off');

xNext = mg;
yNext = yNext - h_edit - mg - h_txt;

h.tm.text_conf1 =  uicontrol('style','text','parent',h.tm.uipanel_range,...
    'string','Select trace if:','fontunits','pixels','position',...
    [xNext,yNext,w_pan_slct-2*mg,h_txt],'fontsize',fntS,...
    'horizontalalignment','left');

yNext = yNext - mg - h_txt;

str_pop = {'at least','at most','between'};
h.tm.popupmenu_cond = uicontrol('style','popupmenu','parent',...
    h.tm.uipanel_range,'string',str_pop,'tooltipstring',...
    'Select a condition','position',[xNext,yNext,0.5*w_pop,h_pop],...
    'fontunits','pixels','fontsize',fntS,'callback',...
    {@popupmenu_cond_Callback,h_fig});

xNext = xNext + 0.5*w_pop + mg/2;

h.tm.edit_conf1 = uicontrol('style','edit','parent',h.tm.uipanel_range,...
    'string','50','position',[xNext,yNext,w_edit,h_edit],'fontunits',...
    'pixels','fontsize',fntS,'callback',{@edit_conf_Callback,h_fig});

xNext = xNext + w_edit;
yNext = yNext + (h_edit-h_txt)/2;

h.tm.text_and = uicontrol('style','text','parent',h.tm.uipanel_range,...
    'string','and','position',[xNext,yNext,w_txt3,h_txt],'fontunits',...
    'pixels','fontsize',fntS,'horizontalalignment','center','enable',...
    'off');

xNext = xNext + w_txt3;
yNext = yNext - (h_edit-h_txt)/2;

h.tm.edit_conf2 = uicontrol('style','edit','parent',h.tm.uipanel_range,...
    'string','100','position',[xNext,yNext,w_edit,h_edit],'fontunits',...
    'pixels','fontsize',fntS,'callback',{@edit_conf_Callback,h_fig},...
    'enable','off');

xNext = mg;
yNext = yNext - mg - h_pop;

str_pop = {'percents of the trace','data points'};
h.tm.popupmenu_units = uicontrol('style','popupmenu','parent',...
    h.tm.uipanel_range,'string',str_pop,'tooltipstring',...
    'Select a condition','position',[xNext,yNext,w_pan_slct-2*mg,h_pop],...
    'fontunits','pixels','fontsize',fntS,'callback',...
    {@popupmenu_units_Callback,h_fig});

yNext = yNext - mg - h_txt;

h.tm.text_conf2 =  uicontrol('style','text','parent',h.tm.uipanel_range,...
    'string','are included in the range.','position',...
    [xNext,yNext,w_pan_slct-2*mg,h_txt],'fontunits','pixels','fontsize',...
    fntS,'horizontalalignment','left');

yNext = yNext - mg_big - h_txt;

h.tm.text_Npop = uicontrol('style','text','parent',h.tm.uipanel_range,...
    'string','subgroup size: 0 molecule','position',...
    [xNext,yNext,w_pan_slct-2*mg,h_txt],'fontunits','pixels','fontsize',...
    fntS,'horizontalalignment','left','fontweight','bold');

yNext = yNext - mg - h_but;

h.tm.pushbutton_saveRange = uicontrol('style','pushbutton','parent',...
    h.tm.uipanel_range,'string','Save subgroup','tooltipstring',...
    'Save the range to tag the corresponding molecule subgroup','position',...
    [xNext,yNext,w_lst,h_but],'fontunits','pixels','fontsize',...
    fntS,'callback',{@pushbutton_saveRange_Callback,h_fig},'enable','off');

yNext = yNext - mg_big - h_edit;

h.tm.text_pop = uicontrol('style','text','parent',h.tm.uipanel_range,...
    'string','Molecule subgroups:','position',...
    [xNext,yNext,w_pan_slct-2*mg,h_txt],'fontunits','pixels','fontsize',...
    fntS,'horizontalalignment','left','fontweight','bold','enable','off');

xNext = mg;
yNext = yNext - mg - h_lst;

h.tm.listbox_ranges = uicontrol('style','listbox','parent',...
    h.tm.uipanel_range,'string',{'no range'},'tooltipstring',...
    'Select a range','position',[xNext,yNext,w_lst,h_lst],'fontunits',...
    'pixels','fontsize',fntS,'callback',{@listbox_ranges_Callback,h_fig},...
    'enable','off');

yNext = yNext - mg - h_but;

h.tm.pushbutton_dismissRange = uicontrol('style','pushbutton','parent',...
    h.tm.uipanel_range,'string','Dismiss subgroup','tooltipstring',...
    'Delete selected subgroup','position',[xNext,yNext,w_lst,h_but],...
    'fontunits','pixels','fontsize',fntS,'callback',...
    {@pushbutton_dismissRange_Callback,h_fig},'enable','off');

yNext = yNext - mg_big - h_edit;

h.tm.text_tag = uicontrol('style','text','parent',h.tm.uipanel_range,...
    'string','Subgroup tags:','position',...
    [xNext,yNext,w_pan_slct-2*mg,h_txt],'fontunits','pixels','fontsize',...
    fntS,'horizontalalignment','left','fontweight','bold','enable','off');

yNext = yNext - mg - h_but;

h.tm.pushbutton_addTag2pop = uicontrol('style','pushbutton', ...
    'Parent',h.tm.uipanel_range,'units','pixel','position', ...
    [xNext yNext w_edit h_but],'string','Tag','callback', ...
    {@pushbutton_addTag2pop_Callback,h_fig},'enable','off');

xNext = xNext + w_edit + mg;

str_pop = colorTagNames(h_fig);
h.tm.popupmenu_defTagPop = uicontrol('style','popup','parent',...
    h.tm.uipanel_range,'units','pixel','enable','off','position',...
    [xNext yNext w_pan_slct-3*mg-w_edit h_pop],'string',str_pop,'value',1);

xNext = mg;
yNext = yNext - mg - h_lst;

str_lst = {'no tag'};
h.tm.listbox_popTag = uicontrol('style','listbox','parent',...
    h.tm.uipanel_range,'units','pixel','enable','off','position',...
    [xNext yNext w_pan_slct-2*mg h_lst],'string',str_lst);

yNext = yNext - mg - h_but;

h.tm.pushbutton_remPopTag = uicontrol('style','pushbutton','parent',...
    h.tm.uipanel_range,'units','pixel','enable','off','position',...
    [xNext yNext w_pan_slct-2*mg h_but],'string','Untag','callback',...
    {@pushbutton_remPopTag_Callback,h_fig});

h.tm.pushbutton_applyTag = uicontrol('style','pushbutton','parent',...
    h.tm.uipanel_range,'units','pixel','enable','off','position',...
    [xNext mg w_pan_slct-2*mg yNext-2*mg],'string',...
    'APPLY TAG TO MOLECULES','callback',...
    {@pushbutton_applyTag_Callback,h_fig},'fontweight','bold');


%% build panel video view

xNext = 2*mg;
yNext = h_pan_tool - 2*mg - h_pop + (h_pop-h_txt)/2;

h.tm.text_exc = uicontrol('style','text','parent',h.tm.uipanel_videoView,...
    'units','pixels','position',[xNext,yNext,0.7*w_cb,h_txt],'fontunits',...
    'pixels','fontsize',fntS,'string','Select laser wavelength:',...
    'fontweight','bold','horizontalalignment','left');

xNext = xNext + 0.7*w_cb + mg;
yNext = yNext - (h_pop-h_txt)/2;

str_pop = getStrPop('exc',...
    h.param.ttPr.proj{h.param.ttPr.curr_proj}.excitations);
if numel(str_pop)>1
    str_pop = [str_pop 'all'];
end
h.tm.popupmenu_VV_exc = uicontrol('style','popup','parent',...
    h.tm.uipanel_videoView,'units','pixel','string',str_pop,'position',...
    [xNext,yNext,0.3*w_cb,h_pop],'value',numel(str_pop),'callback',...
    {@popupmenu_VV_exc_Callback,h_fig});

xNext = 2*mg;
yNext = yNext - mg_big - h_pop + (h_pop-h_txt)/2;

h.tm.text_VV_mol = uicontrol('style','text','parent',...
    h.tm.uipanel_videoView,'units','pixels','position',...
    [xNext,yNext,0.5*w_cb,h_txt],'fontunits','pixels','fontsize',fntS,...
    'string','Show molecules:','fontweight','bold','horizontalalignment',...
    'left');

xNext = xNext + 0.5*w_cb + mg;
yNext = yNext - (h_pop-h_txt)/2;

str_pop = {'selected','unselected','all'};
h.tm.popupmenu_VV_mol = uicontrol('style','popup','parent',...
    h.tm.uipanel_videoView,'units','pixel','value',3,'position',...
    [xNext,yNext,0.5*w_cb,h_pop],'string',str_pop,'callback',...
    {@popupmenu_VV_mol_Callback,h_fig});

xNext = 2*mg;
yNext = yNext - mg_big - h_pop;

h.tm.checkbox_VV_tag0 = uicontrol('style','checkbox','parent',...
    h.tm.uipanel_videoView,'units','pixels','fontunits','pixels',...
    'fontsize',fntS,'position',[xNext,yNext,w_cb2,h_cb],'string',...
    'show','callback',{@checkbox_VV_tag0_Callback,h_fig});

xNext = xNext + w_cb2 + mg;

h.tm.edit_VV_tag0 = uicontrol('style','edit','parent',...
    h.tm.uipanel_videoView,'units','pixels','fontunits','pixels',...
    'fontsize',fntS,'position',[xNext,yNext,w_edit2,h_cb],'string',...
    'not labelled','enable','off');

xNext = w_cb + 3*mg;
yNext = h_pan_tool - h_pop - mg - h_axes4;

% modified by MH, 24.8.2019
h.tm.axes_videoView = axes('parent',h.tm.uipanel_videoView,'units',...
    'pixels','fontunits','pixels','fontsize',fntS,'activepositionproperty',...
    'outerposition','gridlineStyle',':','nextPlot','replace');
%     'outerposition','gridlineStyle',':','nextPlot','replacechildren');

ylim(h.tm.axes_videoView,[0 10000]);
ylabel(h.tm.axes_videoView,'x-position (pixel)');
xlabel(h.tm.axes_videoView,'y-position (pixel)');
title(h.tm.axes_videoView,'Average video frame');
pos = getRealPosAxes([xNext,yNext,w_axes4,h_axes4],...
    get(h.tm.axes_videoView,'tightinset'),'traces'); 
pos(3) = pos(3) - fntS;
pos(1) = pos(1) + fntS;
set(h.tm.axes_videoView,'Position',pos);

guidata(h_fig,h);
updatePanel_VV(h_fig);
h = guidata(h_fig);

    
%% save and finalize figure
    
% save controls
guidata(h_fig, h);

% set all positions and dimensions to normalized 
setProp(get(h.tm.figure_traceMngr, 'Children'), 'Units', 'normalized');

% set all font units to pixels
setProp(get(h.tm.figure_traceMngr, 'Children'), 'FontUnits', 'pixels');

% store relevant parameters to used when reducing panel "Overall plot"
pos_button = get(h.tm.pushbutton_reduce, 'Position');
pos_panelAll_open = get(h.tm.uipanel_overall, 'Position');
pos_panelSingle_open = get(h.tm.uipanel_overview, 'Position');
dat.arrow = flipdim(arrow_up,1);% close
dat.open = 1;
h_panelAll_close = pos_button(4);
dat.pos_all = [pos_panelAll_open(1) ...
    pos_panelAll_open(2)+pos_panelAll_open(4)-h_panelAll_close ...
    pos_panelAll_open(3) h_panelAll_close];% close
dat.pos_single = [pos_panelSingle_open(1) pos_panelSingle_open(2) ...
    pos_panelAll_open(3) (pos_panelSingle_open(4)+ ...
    pos_panelAll_open(4)-h_panelAll_close)];% close
dat.tooltip = 'Show overall panel';% close
dat.visible = 'off';
set(h.tm.pushbutton_reduce, 'UserData', dat);

% make figure visible
set(h.tm.figure_traceMngr, 'Visible', 'on');

% set jet colormap
colormap(h.tm.figure_traceMngr,'jet');

% switch to default tool interface
switchPan_TM(h.tm.togglebutton_overview,[],h_fig);
    
