function h = build_TPexport_panelHistogram(h,q)

% default
str0 = 'Export histograms';
str1 = 'Histograms to export:';
str2 = 'min';
str3 = 'bin';
str4 = 'max';
str5 = 'intensities';
str6 = 'FRET';
str7 = 'stoichiometries';
str8 = 'save discretised histograms';
str9 = 'No histogram file';
ttstr0 = 'counts';

% get project parameters
p = h.param;
perSec = p.proj{p.curr_proj}.cnt_p_sec;
if perSec
    ttstr0 = [ttstr0 ' per sec'];
end

% parents
fig0 = h.figure_MASH;
pan = h.optExpTr.uipanel_hist;

% dimensions
wrb0 = getUItextWidth(str0,q.fntun,q.fntsz1,'normal',q.tbl)+q.wbox;
wtxt0 = getUItextWidth(str1,q.fntun,q.fntsz1,'normal',q.tbl);
wcb0 = getUItextWidth(maxlengthstr({str5,str6,str7}),q.fntun,q.fntsz1,'normal',q.tbl)+q.wbox;
wcb1 = getUItextWidth(str8,q.fntun,q.fntsz1,'normal',q.tbl)+q.wbox;
wrb1 = getUItextWidth(str9,q.fntun,q.fntsz1,'normal',q.tbl)+q.wbox;
hpan = 2*q.mg+q.htxt0+q.mg/2+q.htxt0+q.hedit0+2*(q.hedit0+q.mg/2)+...
    3*(q.hedit0+q.mg)+q.mg;
wpan = 2*q.mg+max([wrb0,wtxt0,wrb1,wcb1,wcb0+q.mg+3*q.wedit0]);

pan.Position([3,4]) = [wpan,hpan];

% GUI
x = q.mg;
y = hpan-2*q.mg-q.hedit0;

h.optExpTr.radiobutton_saveHist = uicontrol('Style', 'radiobutton', 'Parent',...
    pan, 'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'String', str0, 'Position', [x y wrb0 q.hedit0], 'Callback', ...
    {@radiobutton_saveHist_Callback, fig0});

y = y-q.mg-q.htxt0;

h.optExpTr.text_hist2exp = uicontrol('Style', 'text', 'Parent', pan, ...
    'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'String', str1, 'Position', [x y wtxt0 q.htxt0], 'HorizontalAlignment',...
    'left');

x = x+wcb0;
y = y-q.mg/2-q.htxt0;

h.optExpTr.text_min = uicontrol('Style', 'text', 'Parent', pan, 'Units', ...
    q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, 'String', str2, ...
    'Position', [x y q.wedit0 q.htxt0], 'HorizontalAlignment', 'center');

x = x+q.mg/2+q.wedit0;

h.optExpTr.text_bin = uicontrol('Style', 'text', 'Parent', pan, 'Units', ...
    q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, 'String', str3, ...
    'Position', [x y q.wedit0 q.htxt0], 'HorizontalAlignment', 'center');

x = x+q.mg/2+q.wedit0;

h.optExpTr.text_max = uicontrol('Style', 'text', 'Parent',...
    pan, 'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'String', str4, 'Position', [x y q.wedit0 q.htxt0], ...
    'HorizontalAlignment', 'center');

x = q.mg;
y = y-q.hedit0;

h.optExpTr.checkbox_histI = uicontrol('Style', 'checkbox', 'Parent',...
    pan, 'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'String', str5, 'Callback', {@checkbox_histI_Callback, fig0}, ...
    'Position', [x y wcb0 q.hedit0]);

x = x+wcb0;

h.optExpTr.edit_minI = uicontrol('Style', 'edit', 'Parent',...
    pan, 'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'Position', [x y q.wedit0 q.hedit0], 'Callback', ...
    {@edit_minI_Callback, fig0}, 'TooltipString', ttstr0);

x = x+q.mg/2+q.wedit0;

h.optExpTr.edit_binI = uicontrol('Style', 'edit', 'Parent',...
    pan, 'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'Position', [x y q.wedit0 q.hedit0], 'Callback', ...
    {@edit_binI_Callback, fig0}, 'TooltipString', ttstr0);

x = x+q.mg/2+q.wedit0;

h.optExpTr.edit_maxI = uicontrol('Style', 'edit', 'Parent',...
    pan, 'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'Position', [x y q.wedit0 q.hedit0], 'Callback', ...
    {@edit_maxI_Callback, fig0}, 'TooltipString', ttstr0);

x = q.mg;
y = y-q.mg/2-q.hedit0;

h.optExpTr.checkbox_histFRET = uicontrol('Style', 'checkbox', 'Parent',...
    pan, 'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'String', str6, 'Callback', {@checkbox_histFRET_Callback, fig0}, ...
    'Position', [x y wcb0 q.hedit0]);

x = x + wcb0;

h.optExpTr.edit_minFRET = uicontrol('Style', 'edit', 'Parent',...
    pan, 'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'Position', [x y q.wedit0 q.hedit0], 'Callback', ...
    {@edit_minFRET_Callback, fig0});

x = x+q.mg/2+q.wedit0;

h.optExpTr.edit_binFRET = uicontrol('Style', 'edit', 'Parent',...
    pan, 'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'Position', [x y q.wedit0 q.hedit0], 'Callback', ...
    {@edit_binFRET_Callback, fig0});

x = x+q.mg/2+q.wedit0;

h.optExpTr.edit_maxFRET = uicontrol('Style', 'edit', 'Parent',...
    pan, 'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'Position', [x y q.wedit0 q.hedit0], 'Callback', ...
    {@edit_maxFRET_Callback, fig0});

x = q.mg;
y = y-q.mg/2-q.hedit0;

h.optExpTr.checkbox_histS = uicontrol('Style', 'checkbox', 'Parent',...
    pan, 'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'String', str7, 'Callback', {@checkbox_histS_Callback, fig0}, ...
    'Position', [x y wcb0 q.hedit0]);

x = x + wcb0;

h.optExpTr.edit_minS = uicontrol('Style', 'edit', 'Units', q.posun, ...
    'Parent', pan, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'Position', [x y q.wedit0 q.hedit0], 'Callback', ...
    {@edit_minS_Callback, fig0});

x = x+q.mg/2+q.wedit0;

h.optExpTr.edit_binS = uicontrol('Style', 'edit', 'Units', q.posun, ...
    'Parent', pan, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'Position', [x y q.wedit0 q.hedit0], 'Callback', ...
    {@edit_binS_Callback, fig0});

x = x+q.mg/2+q.wedit0;

h.optExpTr.edit_maxS = uicontrol('Style', 'edit', 'Parent', pan, 'Units', ...
    q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, 'Position', ...
    [x y q.wedit0 q.hedit0], 'Callback', {@edit_maxS_Callback, fig0});

x = q.mg;
y = y-q.mg-q.hedit0;

h.optExpTr.checkbox_histDiscr = uicontrol('Style', 'checkbox', 'Parent',...
    pan, 'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'String', str8, 'Callback', {@checkbox_histDiscr_Callback, fig0}, ...
    'Position', [x y wcb1 q.hedit0]);

x = q.mg;
y = y-q.mg-q.hedit0;

h.optExpTr.radiobutton_noHist = uicontrol('Style', 'radiobutton', 'Parent',...
    pan, 'Units', q.posun, 'FontUnits', q.fntun, 'FontSize', q.fntsz1, ...
    'String', str9, 'Position', [x y wrb1 q.hedit0], 'Callback', ...
    {@radiobutton_noHist_Callback, fig0});