function setDefault_HA(h_fig,p)
% setDefault_HA(h_fig,p)
%
% Set Histogram analysis module to default values and update interface parameters
%
% h_fig: handle to main figure
% p: structure that must contain default parameters as generated by getDefault_HA

% get interface parameters
h = guidata(h_fig);

% empty project list
nProj = numel(h.listbox_proj.String);
for proj = nProj:-1:1
    set(h.listbox_proj,'value',proj);
    listbox_projLst_Callback(h.listbox_proj,[],h_fig);
    pushbutton_closeProj_Callback(h.pushbutton_closeProj,[],h_fig,true);
end

% import default project
pushbutton_openProj_Callback({p.annexpth,p.mash_file},[],h_fig);

% switch to HA's module
switchPan(h.togglebutton_HA,[],h_fig);

% set default histogram and plot parameters
h_but = getHandlePanelExpandButton(h.uipanel_HA_histogramAndPlot,h_fig);
if strcmp(h_but.String,char(9660))
    pushbutton_panelCollapse_Callback(h_but,[],h_fig);
end
set_HA_histplot(p.histDat,p.histTag,p.histPrm,h_fig);

% set default state configuration parameters
h_but = getHandlePanelExpandButton(h.uipanel_HA_stateConfiguration,h_fig);
if strcmp(h_but.String,char(9660))
    pushbutton_panelCollapse_Callback(h_but,[],h_fig);
end
set_HA_stateConfig(p.cnfgPrm,h_fig);

