function setDefault_HA(h_fig,p)
% setDefault_HA(h_fig,p)
%
% Set Histogram analysis module to default values and update interface parameters
%
% h_fig: handle to main figure
% p: structure that must contain default parameters as generated by getDefault_HA

% get interface parameters
h = guidata(h_fig);

% empty project list
nProj = numel(get(h.listbox_thm_projLst,'string'));
proj = nProj;
while proj>0
    set(h.listbox_thm_projLst,'value',proj);
    listbox_thm_projLst_Callback(h.listbox_thm_projLst,[],h_fig);
    pushbutton_thm_rmProj_Callback(h.pushbutton_thm_rmProj,[],h_fig);
    proj = proj-1;
end

% import default project
pushbutton_thm_addProj_Callback({p.annexpth,p.mash_file},[],h_fig);

% set default histogram and plot parameters
set_HA_histplot(p.histDat,p.histTag,p.histPrm,h_fig);

% set default state configuration parameters
set_HA_stateConfig(p.cnfgPrm,h_fig);

