function setDefault_VP(h_fig,p,prefix)
% setDefault_VP(h_fig,p,prefix)
%
% Set Video processing module to default values and update interface parameters
%
% h_fig: handle to main figure
% p: structure that must contain default parameters as generated by getDefault_VP
% prefix: string to add at the beginning of each action string (usually a apecific indent)

% get interface parameters
h = guidata(h_fig);

% set cursor to zoom
switchMovTool(h.togglebutton_zoom,[],h_fig);

% set defaults in panel Plot
set(h.popupmenu_colorMap,'value',p.cmap);
popupmenu_colorMap_Callback(h.popupmenu_colorMap,[],h_fig);

% set defaults in panel Edit and export video
set_VP_imFilters(p.bg_corr,p.bg_prm,p.bg_all,[p.annexpth,filesep,p.bg_file],...
    p.nChan,h_fig);

set(h.edit_startMov,'string',num2str(p.vid_start));
edit_startMov_Callback(h.edit_startMov,[],h_fig);

set(h.edit_endMov,'string',num2str(p.vid_end));
edit_endMov_Callback(h.edit_endMov,[],h_fig);

set(h.edit_ivMov,'string',num2str(p.vid_iv));
edit_ivMov_Callback(h.edit_ivMov,[],h_fig);

% set defaults in panel Average image
set(h.edit_aveImg_iv,'string',num2str(p.ave_iv));
edit_aveImg_iv_Callback(h.edit_aveImg_iv,[],h_fig);

set(h.edit_aveImg_start,'string',num2str(p.ave_start));
edit_aveImg_start_Callback(h.edit_aveImg_start,[],h_fig);

set(h.edit_aveImg_end,'string',num2str(p.ave_end));
edit_aveImg_end_Callback(h.edit_aveImg_end,[],h_fig);

% set defaults in panel Molecule coordinates
set_VP_spotFinder(p.sf_meth,p.sf_fit,[],p.sf_prm,p.nChan,h_fig);

% set defaults in panel Intensity integration
set(h.edit_TTgen_dim,'string',num2str(p.pixDim));
edit_TTgen_dim_Callback(h.edit_TTgen_dim,[],h_fig);

set(h.edit_intNpix,'string',num2str(p.nPix));
edit_intNpix_Callback(h.edit_intNpix,[],h_fig);

