function setDefault_VP(h_fig,p)
% setDefault_VP(h_fig,p)
%
% Set Video processing module to default values and update interface parameters
%
% h_fig: handle to main figure
% p: structure that must contain default parameters as generated by getDefault_VP

% get interface parameters
h = guidata(h_fig);

% free memory
pushbutton_VP_freeMem_Callback(h.pushbutton_VP_freeMem,[],h_fig);

% import video
disp(cat(2,'import default video file ',p.vid_files{1}));
pushbutton_loadMov_Callback({p.annexpth,p.vid_files{1}},[],h_fig);

% set cursor to zoom
switchMovTool(h.togglebutton_zoom,[],h_fig);

% set defaults in panel Plot
set(h.checkbox_int_ps,'value',p.perSec);
checkbox_int_ps_Callback(h.checkbox_int_ps,[],h_fig);

set(h.popupmenu_colorMap,'value',p.cmap);
popupmenu_colorMap_Callback(h.popupmenu_colorMap,[],h_fig);

% set defaults in panel Edit and export video
set_VP_imFilters(p.bg_corr,p.bg_prm,p.bg_all,h_fig);

set(h.edit_startMov,'string',num2str(p.vid_start));
edit_startMov_Callback(h.edit_startMov,[],h_fig);

set(h.edit_endMov,'string',num2str(p.vid_end));
edit_endMov_Callback(h.edit_endMov,[],h_fig);

% set defaults in panel Experiment settings
set(h.edit_nChannel,'string',num2str(p.nChan));
edit_nChannel_Callback(h.edit_nChannel,[],h_fig);

set(h.edit_rate,'string',num2str(p.expT));
edit_rate_Callback(h.edit_rate,[],h_fig);

set_VP_lasers(p.nL,p.wl(1:p.nL),h_fig);

set_VP_projOpt(p,h_fig);

% set defaults in panel Molecule coordinates
set(h.edit_aveImg_iv,'string',num2str(p.ave_iv));
edit_aveImg_iv_Callback(h.edit_aveImg_iv,[],h_fig);

set(h.edit_aveImg_start,'string',num2str(p.ave_start));
edit_aveImg_start_Callback(h.edit_aveImg_start,[],h_fig);

set(h.edit_aveImg_end,'string',num2str(p.ave_end));
edit_aveImg_end_Callback(h.edit_aveImg_end,[],h_fig);

set_VP_spotFinder(p.sf_meth,p.sf_fit,p.sf_all,p.sf_prm,h_fig);

% set defaults in panel Intensity integration
set(h.edit_intNpix,'string',num2str(p.nPix));
edit_intNpix_Callback(h.edit_intNpix,[],h_fig);

set(h.edit_TTgen_dim,'string',num2str(p.pixDim));
edit_TTgen_dim_Callback(h.edit_TTgen_dim,[],h_fig);

set(h.checkbox_meanVal,'value',p.pixAve);
checkbox_meanVal_Callback(h.checkbox_meanVal,[],h_fig);

