function q = buildPanelData(q,p,h_fig)

% default
fact = 5;
ud = 1;
str0 = 'x-data';
str1 = 'x-value';
str2 = {'original time traces (frame-wise)',...
    'state trajectories (frame-wise)',...
    'means (molecule-wise)',...
    'minima (molecule-wise)',...
    'maxima (molecule-wise)',...
    'medians (molecule-wise)',...
    'SNR (molecule-wise)',...
    'bleaching cutoff (molecule-wise)',...
    'nb. of states (molecule-wise)',...
    'nb. of transitions (molecule-wise)',...
    'mean state dwell time (molecule-wise)',...
    'state values (state-wise)',...
    'state dwell times (state-wise)',...
    'state lifetimes (state-wise)'};
str3 = 'x min';
str4 = 'x max';
str5 = 'nbins';
str6 = 'y-data';
str7 = 'y-value';
str8 = 'y min';
str9 = 'y max';
str10 = 'nbins';
str11 = 'gauss.';
str12 = 'single count';
str13 = 'Export to .txt file';
ttstr0 = wrapHtmlTooltipString('Select the <b>data</b> to represent on <b>the x-axis</b> of the histogram');
ttstr1 = wrapHtmlTooltipString('Select the <b>value</b> to histogram on the <b>x-axis</b> of the histogram');
ttstr2 = wrapHtmlTooltipString('<b>Lower</b> bound of <b>x-axis</b>');
ttstr3 = wrapHtmlTooltipString('<b>Upper</b> bound of <b>x-axis</b>');
ttstr4 = wrapHtmlTooltipString('<b>Number of binning</b> intervals in <b>x-axis</b>');
ttstr5 = wrapHtmlTooltipString('Select the <b>data</b> to represent on the <b>y-axis</b> of the 2D-histogram');
ttstr6 = wrapHtmlTooltipString('Select the <b>value</b> to histogram on the <b>y-axis</b> of the 2D-histogram');
ttstr7 = wrapHtmlTooltipString('<b>Lower</b> bound of <b>y-axis</b>');
ttstr8 = wrapHtmlTooltipString('<b>Upper</b> bound of <b>y-axis</b>');
ttstr9 = wrapHtmlTooltipString('<b>Number of binning</b> intervals in <b>y-axis</b>');
ttstr10 = wrapHtmlTooltipString('<b>Data count:</b> when activated, data values appearing multiple times in the same trajectories are counted once, otherwise it is counted as many times as it appear in each trajectory; single data count allows to scale equally the rapid and slow state interconversions in the TDP.');
ttstr11 = wrapHtmlTooltipString('<b>Gaussian filter:</b> when activated, the TDP is convoluted with a 2D Gaussian; Gaussian convolution eases the identification of transition clusters.');
ttstr12 = wrapHtmlTooltipString('<b>Export histogram</b> data to a text file.');

% parent
h_pan = q.uipanel_data;

% dimensions
pospan = get(h_pan,'position');
wpop2 = (pospan(3)-2*p.mg-p.mg/fact)/2;
wedit2 = (pospan(3)-2*p.mg-2*p.mg/fact)/3;
wcb0 = getUItextWidth(str11,p.fntun,p.fntsz,'normal',p.tbl)+p.wbox;
wcb1 = pospan(3)-wcb0-2*p.mg;
wbut = pospan(3)-2*p.mg;

% list strings
str_pop = getStrPlot_overall(h_fig);
str_popx = str_pop{2};
str_popy = ['none',str_popx];

x = p.mg;
y = pospan(4)-p.mgbig-p.htxt;

q.text_xdata = uicontrol('style','text','parent',h_pan,'units',p.posun,...
    'position',[x,y,wpop2,p.htxt],'fontunits',p.fntun,'fontsize',p.fntsz,...
    'string',str0);

x = x+wpop2+p.mg/fact;

q.text_xval = uicontrol('style','text','parent',h_pan,'units',p.posun,...
    'position',[x,y,wpop2,p.htxt],'fontunits',p.fntun,'fontsize',p.fntsz,...
    'string',str1);

x = p.mg;
y = y-p.hpop;

q.popupmenu_selectXdata = uicontrol('style','popupmenu','parent',h_pan,...
    'units',p.posun,'position',[x,y,wpop2,p.hpop],'fontunits',p.fntun,...
    'fontsize',p.fntsz,'string',str_popx,'tooltipstring',ttstr0,...
    'callback',{@popupmenu_selectData_Callback,h_fig});

x = x+wpop2+p.mg/fact;
 
q.popupmenu_selectXval = uicontrol('style','popupmenu','parent',h_pan,...
    'units',p.posun,'position',[x,y,wpop2,p.hpop],'fontunits',p.fntun,...
    'fontsize',p.fntsz,'string',str2,'tooltipstring',ttstr1,'callback',...
    {@popupmenu_selectData_Callback,h_fig},'userdata',ud);

x = p.mg;
y = y-p.mg/2-p.htxt;

q.text_xlow = uicontrol('style','text','parent',h_pan,'units',p.posun,...
    'string',str3,'position',[x,y,wedit2,p.htxt],'fontunits',p.fntun,...
    'fontsize',p.fntsz);

x = x+wedit2+p.mg/fact;

q.text_xup = uicontrol('style','text','parent',h_pan,'units',p.posun,...
    'string',str4,'position',[x,y,wedit2,p.htxt],'fontunits',p.fntun,...
    'fontsize',p.fntsz);

x = x+wedit2+p.mg/fact;

q.text_xniv = uicontrol('style','text','parent',h_pan,'units',p.posun,...
    'string',str5,'position',[x,y,wedit2,p.htxt],'fontunits',p.fntun,...
    'fontsize',p.fntsz);

x = p.mg;
y = y-p.hedit;

q.edit_xlow = uicontrol('style','edit','parent',h_pan,'units',p.posun,...
    'position',[x,y,wedit2,p.hedit],'fontunits',p.fntun,'fontsize',p.fntsz,...
    'string','','tooltipstring',ttstr2,'callback',...
    {@edit_xlow_Callback,h_fig});

x = x+wedit2+p.mg/fact;

q.edit_xup = uicontrol('style','edit','parent',h_pan,'units',p.posun,...
    'position',[x,y,wedit2,p.hedit],'fontunits',p.fntun,'fontsize',...
    p.fntsz,'string','','tooltipstring',ttstr3,'callback',...
    {@edit_xup_Callback,h_fig});

x = x+wedit2+p.mg/fact;

q.edit_xniv = uicontrol('style','edit','parent',h_pan,'units',p.posun,...
    'string','','tooltipstring',ttstr4,'position',[x,y,wedit2,p.hedit],...
    'fontunits',p.fntun,'fontsize',p.fntsz,'callback',...
    {@edit_xniv_Callback,h_fig});

y = y-p.mg-p.htxt;
x = p.mg;

q.text_ydata = uicontrol('style','text','parent',h_pan,'units',p.posun,...
    'position',[x,y,wpop2,p.htxt],'fontunits',p.fntun,'fontsize',p.fntsz,...
    'string',str6);

x = x+wpop2+p.mg/fact;

q.text_yval = uicontrol('style','text','parent',h_pan,'units',p.posun,...
    'position',[x,y,wpop2,p.htxt],'fontunits',p.fntun,'fontsize',p.fntsz,...
    'string',str7);

x = p.mg;
y = y-p.hpop;

q.popupmenu_selectYdata = uicontrol('style','popupmenu','parent',h_pan,...
    'units',p.posun,'position',[x,y,wpop2,p.hpop],'fontunits',p.fntun,...
    'fontsize',p.fntsz,'string',str_popy,'tooltipstring',ttstr5,...
    'callback',{@popupmenu_selectData_Callback,h_fig});

x = x+wpop2+p.mg/fact;
 
q.popupmenu_selectYval = uicontrol('style','popupmenu','parent',...
    h_pan,'units',p.posun,'string',str2,'tooltipstring',ttstr6,'position',...
    [x,y,wpop2,p.hpop],'fontunits',p.fntun,'fontsize',p.fntsz,'callback',...
    {@popupmenu_selectData_Callback,h_fig},'userdata',ud);

x = p.mg;
y = y-p.mg/2-p.htxt;

q.text_ylow = uicontrol('style','text','parent',h_pan,'units',p.posun,...
    'string',str8,'position',[x,y,wedit2,p.htxt],'fontunits',p.fntun,...
    'fontsize',p.fntsz,'enable','off');

x = x+wedit2+p.mg/fact;

q.text_yup = uicontrol('style','text','parent',h_pan,'units',p.posun,...
    'string',str9,'position',[x,y,wedit2,p.htxt],'fontunits',p.fntun,...
    'fontsize',p.fntsz,'enable','off');

x = x+wedit2+p.mg/fact;

q.text_yniv = uicontrol('style','text','parent',h_pan,'units',p.posun,...
    'string',str10,'position',[x,y,wedit2,p.htxt],'fontunits',p.fntun,...
    'fontsize',p.fntsz,'enable','off');

x = p.mg;
y = y-p.hedit;

q.edit_ylow = uicontrol('style','edit','parent',h_pan,'units',p.posun,...
    'string','','tooltipstring',ttstr7,'position',[x,y wedit2,p.hedit],...
    'fontunits',p.fntun,'fontsize',p.fntsz,'callback',...
    {@edit_ylow_Callback,h_fig},'enable','off');

x = x+wedit2+p.mg/fact;

q.edit_yup = uicontrol('style','edit','parent',h_pan,'units',p.posun,...
    'string','','tooltipstring',ttstr8,'position',[x,y,wedit2,p.hedit],...
    'fontunits',p.fntun,'fontsize',p.fntsz,'callback',...
    {@edit_yup_Callback,h_fig},'enable','off');

x = x+wedit2+p.mg/fact;

q.edit_yniv = uicontrol('style','edit','parent',h_pan,'units',p.posun,...
    'string','','tooltipstring',ttstr9,'position',[x,y,wedit2,p.hedit],...
    'fontunits',p.fntun,'fontsize',p.fntsz,'enable','off','callback',...
    {@edit_yniv_Callback,h_fig});

x = p.mg;
y = y-p.mg/2-p.hcb;

q.checkbox_AS_gauss = uicontrol('style','checkbox','parent',h_pan,'units',...
    p.posun,'string',str11,'tooltipstring',ttstr10,'position',...
    [x,y,wcb0,p.hcb],'fontunits',p.fntun,'fontsize',p.fntsz,'enable','off',...
    'callback',{@checkbox_AS_gauss_Callback,h_fig});

x = x+wcb0;

q.checkbox_AS_datcnt = uicontrol('style','checkbox','parent',h_pan,'units',...
    p.posun,'string',str12,'tooltipstring',ttstr11,'position',...
    [x,y,wcb1,p.hcb],'fontunits',p.fntun,'fontsize',p.fntsz,'enable','off',...
    'callback',{@checkbox_AS_datcnt_Callback,h_fig});

x = p.mg;
y = y-p.mg/2-p.hbut;

q.push_AS_export = uicontrol('style','pushbutton','parent',h_pan,'units',...
    p.posun,'string',str13,'tooltipstring',ttstr12,'position',...
    [x,y,wbut,p.hbut],'fontunits',p.fntun,'fontsize',p.fntsz,'callback',...
    {@push_AS_export_Callback,h_fig});


