function data = getFile2sub(str_prompt, h_fig)
% Store data of image file to substract for background correction
% "h_fig" >> MASH figure handle
% "data" >> structure containing image information

% Requires external functions: updateActPan, getFrames.
% Last update: 5th of February 2014 by Mélodie C.A.S Hadzic

h = guidata(h_fig);
data = [];

[fname, pname, o] = uigetfile({ ...
    '*.sif;*.sira;*.tif;*.gif;*.png;*.spe;*.pma', ...
    ['Supported Graphic File Format' ...
    '(*.sif,*.sira,*.tif,*.gif,*.png,*.spe,*.pma)'];
    '*.sif', 'Andor Solis Simple Interaction File Format(*.sif)'; ...
    '*.sira', 'SIRA Graphic File Format(*.sira)'; ...
    '*.tif', 'Tagged Image File Format(*.tif)'; ...
    '*.gif', 'Graphics Interchange Format(*.gif)'; ...
    '*.png', 'Portable Network Graphics(*.png)'; ...
    '*.spe', 'SPE binary File Format(*.spe)'; ...
    '*.pma', 'PMA binary File Format(*.pma)'; ...
    '*.*', 'All File Format(*.*)';}, str_prompt);
    
if ~isempty(fname) && sum(fname)
    cd(pname);
    updateActPan(['First frame of image file ' fname ' from folder:\n' ...
        pname '\nloading for subtraction...'], h_fig);
    file2sub = [pname, fname];
    [data ok] = getFrames(file2sub, 1, [], h_fig);
    if ok
        data.file = file2sub;
    end
end

