function transMat = getTransMat(h_fig)
% getTransMat returns the numerical transition matrice from the edit fields

h = guidata(h_fig);
transMat = ...
    [str2num(get(h.edit11,'String')) str2num(get(h.edit21,'String')) ...
     str2num(get(h.edit31,'String')) str2num(get(h.edit41,'String')) ...
     str2num(get(h.edit51,'String'))
     str2num(get(h.edit12,'String')) str2num(get(h.edit22,'String')) ...
     str2num(get(h.edit32,'String')) str2num(get(h.edit42,'String')) ...
     str2num(get(h.edit52,'String'))
     str2num(get(h.edit13,'String')) str2num(get(h.edit23,'String')) ...
     str2num(get(h.edit33,'String')) str2num(get(h.edit43,'String')) ...
     str2num(get(h.edit53,'String'))
     str2num(get(h.edit14,'String')) str2num(get(h.edit24,'String')) ...
     str2num(get(h.edit34,'String')) str2num(get(h.edit44,'String')) ...
     str2num(get(h.edit54,'String'))
     str2num(get(h.edit15,'String')) str2num(get(h.edit25,'String')) ...
     str2num(get(h.edit35,'String')) str2num(get(h.edit45,'String')) ...
     str2num(get(h.edit55,'String'))];