function setTransMat(transMat, h_fig)
h = guidata(h_fig);

set(h.edit11, 'String', num2str(transMat(1,1)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit21, 'String', num2str(transMat(1,2)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit31, 'String', num2str(transMat(1,3)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit41, 'String', num2str(transMat(1,4)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit51, 'String', num2str(transMat(1,5)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit12, 'String', num2str(transMat(2,1)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit22, 'String', num2str(transMat(2,2)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit32, 'String', num2str(transMat(2,3)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit42, 'String', num2str(transMat(2,4)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit52, 'String', num2str(transMat(2,5)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit13, 'String', num2str(transMat(3,1)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit23, 'String', num2str(transMat(3,2)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit33, 'String', num2str(transMat(3,3)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit43, 'String', num2str(transMat(3,4)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit53, 'String', num2str(transMat(3,5)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit14, 'String', num2str(transMat(4,1)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit24, 'String', num2str(transMat(4,2)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit34, 'String', num2str(transMat(4,3)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit44, 'String', num2str(transMat(4,4)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit54, 'String', num2str(transMat(4,5)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit15, 'String', num2str(transMat(5,1)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit25, 'String', num2str(transMat(5,2)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit35, 'String', num2str(transMat(5,3)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit45, 'String', num2str(transMat(5,4)), 'BackgroundColor', ...
    [1 1 1]);
set(h.edit55, 'String', num2str(transMat(5,5)), 'BackgroundColor', ...
    [1 1 1]);