function setDefault_S(h_fig,p)
% setDefault_S(h_fig,p)
%
% Set Simulattion modeul to default values and update interface parameters
%
% h_fig: handle to main figure
% p: structure that must contain default parameters as generated by getDefault_S

h = guidata(h_fig);

% remove imported coordinates
h_but = getHandlePanelExpandButton(h.uipanel_S_molecules,h_fig);
if strcmp(h_but.String,char(9660))
    pushbutton_panelCollapse_Callback(h_but,[],h_fig);
end
radiobutton_simCoord_Callback(h.radiobutton_randCoord,[],h_fig);

% remove imported presets
set(h.checkbox_simPrmFile,'value',0);
checkbox_simPrmFile_Callback(h.checkbox_simPrmFile,[],h_fig);

% set defaults in panel Video parameters
h_but = getHandlePanelExpandButton(h.uipanel_S_videoParameters,h_fig);
if strcmp(h_but.String,char(9660))
    pushbutton_panelCollapse_Callback(h_but,[],h_fig);
end

set(h.edit_length,'string',num2str(p.L));
edit_length_Callback(h.edit_length,[],h_fig);

set(h.edit_simRate,'string',num2str(p.rate));
edit_simRate_Callback(h.edit_simRate,[],h_fig);

set(h.edit_pixDim,'string',num2str(p.pixdim));
edit_pixDim_Callback(h.edit_pixDim,[],h_fig);

set(h.edit_simBitPix,'string',num2str(p.bitrate));
edit_simBitPix_Callback(h.edit_simBitPix,[],h_fig);

set(h.edit_simMov_w,'string',num2str(p.viddim(1)));
edit_simMov_w_Callback(h.edit_simMov_w,[],h_fig);

set(h.edit_simMov_h,'string',num2str(p.viddim(2)));
edit_simMov_h_Callback(h.edit_simMov_h,[],h_fig);

set_S_camNoise(p.camnoise,p.camprm,h_fig);

% set defaults in panel Molecules
h_but = getHandlePanelExpandButton(h.uipanel_S_molecules,h_fig);
if strcmp(h_but.String,char(9660))
    pushbutton_panelCollapse_Callback(h_but,[],h_fig);
end

set(h.edit_nbMol,'string',num2str(p.N));
edit_nbMol_Callback(h.edit_nbMol,[],h_fig);

set(h.edit_nbStates,'string',num2str(p.J));
edit_nbStates_Callback(h.edit_nbStates,[],h_fig);

set_S_FRETstates(p.J,p.FRET,p.wFRET,h_fig);

set_S_transitionRates(p.J,p.k,h_fig);

set(h.checkbox_photon,'value',p.pc_in);
checkbox_photon_Callback(h.checkbox_photon,[],h_fig);

set(h.edit_totInt,'string',num2str(p.Itot));
edit_totInt_Callback(h.edit_totInt,[],h_fig);

set(h.edit_dstrbNoise,'string',num2str(p.wItot));
edit_dstrbNoise_Callback(h.edit_dstrbNoise,[],h_fig);

set(h.edit_gamma,'string',num2str(p.gamma));
edit_gamma_Callback(h.edit_gamma,[],h_fig);

set(h.edit_gammaW,'string',num2str(p.wGamma));
edit_gammaW_Callback(h.edit_gammaW,[],h_fig);

set(h.edit_simDeD,'string',num2str(p.dE(1)));
edit_simDeD_Callback(h.edit_simDeD,[],h_fig);

set(h.edit_simDeA,'string',num2str(p.dE(2)));
edit_simDeA_Callback(h.edit_simDeA,[],h_fig);

set(h.edit_simBtD,'string',num2str(p.Bt(1)));
edit_simBtD_Callback(h.edit_simBtD,[],h_fig);

set(h.edit_simBtA,'string',num2str(p.Bt(2)));
edit_simBtA_Callback(h.edit_simBtA,[],h_fig);

set_S_photobleaching(p.bleach,p.t_bleach,h_fig);

% set defaults in panel Experimental setup
h_but = getHandlePanelExpandButton(h.uipanel_S_experimentalSetup,h_fig);
if strcmp(h_but.String,char(9660))
    pushbutton_panelCollapse_Callback(h_but,[],h_fig);
end

set_S_psf(p.psf,p.psfW,h_fig);

set_S_defocus(p.defocus,p.defocus_prm,h_fig);

set_S_spatialBG(p.bg,p.bgI,p.bgW,p.annexpth,p.bgImg,h_fig);

set_S_dynamicBG(p.bgDec,p.bgDec_prm,h_fig);

% set defaults in panel Export options
h_but = getHandlePanelExpandButton(h.uipanel_S_exportOptions,h_fig);
if strcmp(h_but.String,char(9660))
    pushbutton_panelCollapse_Callback(h_but,[],h_fig);
end
set_S_fileExport([p.mat p.sira p.avi p.txt p.dt p.log p.coord],h_fig);

set(h.popupmenu_opUnits,'value',p.un_out);
popupmenu_opUnits_Callback(h.popupmenu_opUnits,[],h_fig);

