function setExpSetDefault_S(h_fig0,p)
% setExpSetDefault_S(h_fig,p)
%
% Set experiment settings to default simulation values 
%
% h_fig: handle to main figure
% p: structure that must contain default parameters as generated by getDefault_S

h0 = guidata(h_fig0);
h_fig = h0.figure_setExpSet;
h = guidata(h_fig);

% set project title
set(h.edit_projName,'string',p.projttl);
edit_setExpSet_projName(h.edit_projName,[],h_fig);

% set molecule name
set(h.edit_molName,'string',p.molname);
edit_setExpSet_molName(h.edit_molName,[],h_fig);

% set experimental conditions
tbldat = h.table_cond.Data;
evd = [];
for r = 3:(3+size(p.expcond,1)-1)
    for c = 1:3
        tbldat{r,c} = p.expcond{r-3+1,c};
        set(h.table_cond,'Data',tbldat);
        evd.Indices = [r,c];
        table_setExpSet_cond(h.table_cond,evd,h_fig);
    end
end

% set sampling time
if strcmp(h.edit_splTime.Enable,'on')
    set(h.edit_splTime,'string',num2str(p.splt));
    edit_setExpSet_splTime(h.edit_splTime,[],h_fig);
end

% set plot colors
for chan = 1:size(p.plotclr,1)
    set(h.popup_chanClr,'value',chan);
    popup_setExpSet_chanClr(h.popup_chanClr,[],h_fig);
    push_setExpSet_clr(p.plotclr(chan,:),[],h_fig);
end

% save & close
push_setExpSet_save(h.push_save,[],'sim',h_fig,h_fig0);

