function ttPr_routine(obj, evd, routine, h_fig)

try
    switch routine
        case 1
%             [ST,I] = dbstack;
%             msgbox({['Routine ' num2str(routine) ' is empty'] '' ...
%                 ['To write/modify a routine see file: ' ST.file] ...
%                 ['function: ' ST.name] ['line: ' num2str(ST.line)]}, ...
%                 'Routine error', 'warn');
            routine_clustTDP(h_fig);

        case 2
            [ST,I] = dbstack;
            msgbox({['Routine ' num2str(routine) ' is empty'] '' ...
                ['To write/modify a routine see file: ' ST.file] ...
                ['function: ' ST.name] ['line: ' num2str(ST.line)]}, ...
                'Routine error', 'warn');

        case 3
            [ST,I] = dbstack;
            msgbox({['Routine ' num2str(routine) ' is empty'] '' ...
                ['To write/modify a routine see file: ' ST.file] ...
                ['function: ' ST.name] ['line: ' num2str(ST.line)]}, ...
                'Routine error', 'warn');

        case 4
            [ST,I] = dbstack;
            msgbox({['Routine ' num2str(routine) ' is empty'] '' ...
                ['To write/modify a routine see file: ' ST.file] ...
                ['function: ' ST.name] ['line: ' num2str(ST.line)]}, ...
                'Routine error', 'warn');

    end
    
catch err
    msgbox({['Routine ' num2str(routine) ' is undefined or incorrect.'] ...
        'The error described below occured:' '' ['"' err.message ', ' ...
        'line ' num2str(err.stack(1).line) '".'] '' ['To create or ' ...
        'edit a routine go to file: ' err.stack(1).file] ['function: ' ...
        err.stack(1).name]}, 'Routine error', 'warn');
end
        
