function setDefault_TP(h_fig,p)
% setDefault_TP(h_fig,p)
%
% Set Trace processing module to default values and update interface parameters
%
% h_fig: handle to main figure
% p: structure that must contain default parameters as generated by getDefault_TP

% get interface parameters
h = guidata(h_fig);

% set default sample management parameters

% set default plot parameters

% set default sub-images parameters

% set default background parameters

% set default cross-talks parameters

% set default denoising parameters

% set default photobleaching parameters

% set default factor corrections parameters

% set default find states parameters
