function setDefault_TP(h_fig,p)
% setDefault_TP(h_fig,p)
%
% Set Trace processing module to default values and update interface parameters
%
% h_fig: handle to main figure
% p: structure that must contain default parameters as generated by getDefault_TP

% get interface parameters
h = guidata(h_fig);